// vue-front/src/components/rule/list/RequestList.vue
<template>
  <div class="urm-list">
    <div class="advanced-search-bar">
      <el-form label-width="135px">
        <div class="row" style="margin-top: 10px;">
          <el-form-item :label="$t('label.interfaceId')">
            <el-input v-model="sparam.interfaceId" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.interfaceType')">
            <el-select v-model="sparam.interfaceType" class="search-id">
              <el-option value="" label="ALL"/>
              <el-option v-for="type in infTypes" :value="type.code" :label="type.name" :key="type.code"/>
            </el-select>
          </el-form-item>
          <el-form-item :label="$t('label.requestId')">
            <el-input v-model="sparam.id" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.requestName')">
            <el-input v-model="sparam.name" class="search-name"/>
          </el-form-item>
          <div class="search-buttons">
            <el-button @click.stop="clickTransfer">이관</el-button>
          </div>
        </div>
        <div class="row">
          <el-form-item :label="$t('label.sourceSystem')">
            <el-input v-model="sparam.sendSystemId" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.sndJobCode')">
            <el-input v-model="sparam.sendJobCodeId" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.changeStatus')">
            <el-select v-model="sparam.chgStat" class="search-id">
              <el-option value="" label="ALL"/>
              <el-option v-for="stat in chgStats" :value="stat.code" :label="stat.name" :key="stat.code"/>
            </el-select>
          </el-form-item>
          <el-form-item :label="$t('label.processStatus')">
            <el-select v-model="sparam.processStat" style="width: 150px">
              <el-option value="" label="ALL"/>
              <el-option v-for="stat in procStats" :value="stat.code" :label="stat.name" :key="stat.code"/>
            </el-select>
          </el-form-item>
          <div class="search-buttons">
            <el-button @click.stop="clickEdit()">{{$t('label.add')}}</el-button>
            <el-button @click.stop="clickDelete('selected')" type="danger" plain>{{$t('label.delete')}}</el-button>
          </div>
        </div>
        <div class="row">
          <el-form-item :label="$t('label.targetSystem')">
            <el-input v-model="sparam.rcvSystemId" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.rcvJobCode')">
            <el-input v-model="sparam.rcvJobCodeId" class="search-id"/>
          </el-form-item>
          <el-form-item :label="$t('label.lastChangeDate')">
            <el-date-picker v-model="sparam.chgDate" type="daterange"
              start-placeholder="Start Date" end-placeholder="End Date" style="width: 220px;"/>
          </el-form-item>
          <div class="row">
            <el-form-item label="등록자" label-width="65px">
              <el-checkbox v-model="sparam.cRegId"/>
            </el-form-item>
            <el-form-item label="송신자" label-width="65px">
              <el-checkbox v-model="sparam.cSendAdminId"/>
            </el-form-item>
            <el-form-item label="수신자" label-width="65px">
              <el-checkbox v-model="sparam.cRcvAdminId"/>
            </el-form-item>
          </div>
          <div class="search-buttons">
            <el-button @click.stop="search">{{$t('label.search')}}</el-button>
          </div>
        </div>
      </el-form>
    </div>

    <el-table :data="items" :height="listHeight" border class="table-striped">
      <el-table-column type="selection" width="40"/>
      <el-table-column :label="$t('label.id')" prop="id" width="150"/>
      <el-table-column :label="$t('label.changeStatus')" width="115">
        <template slot-scope="scope">
          <span :style="chgStatStyle(scope.row.chgStat)">{{getTypeStr('chgStat', scope.row.chgStat)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.processStatus')" width="130">
        <template slot-scope="scope">
          <span>{{getTypeStr('procStat', scope.row.processStat)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.interfaceType')" width="80">
        <template slot-scope="scope">
          <span>{{getTypeStr('infType', scope.row.interfaceType)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.name')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.interfaceId')" prop="interfaceId" width="135"/>
      <el-table-column :label="$t('label.sourceMethod')" width="85">
        <template slot-scope="scope">
          <span>{{getTypeStr('sysType', scope.row.sendSystemType)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.targetMethod')" width="85">
        <template slot-scope="scope">
          <span>{{getTypeStr('sysType', scope.row.rcvSystemType)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.sourceSystem')" prop="sendSystem.name" width="110" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.targetSystem')" prop="rcvSystem.name" width="110" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.lastChangeDate')" prop="chgDate" width="150"/>
      <el-table-column width="115" class-name="edit-cell operations">
        <template slot-scope="scope">
          <div>
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row.id)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row.id)" plain/>
            <el-button icon="el-icon-refresh-left" @click.stop="viewHistory(scope.row.id)"/>
          </div>
        </template>
      </el-table-column>
    </el-table>

    <el-pagination background layout="sizes, prev, pager, next, ->, total"
      :total="paging.totalCount" :current-page="paging.curPage"
      :page-sizes="pageSizes" :page-size="sparam.size"
      @size-change="handlePageSizeChange" @current-change="handlePageCurrentChange">
    </el-pagination>

    <el-dialog title="System List" :visible.sync="systemListShow" width="95%" top="8vh" append-to-body :close-on-click-modal="false">
      <SystemList :onlySearch="true" @row-dblclick="cbSystemRowClick"/>
    </el-dialog>
  </div>
</template>

<script>
import RuleList from './RuleList'
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  mixins: [RuleList],
  data () {
    return {
      path: 'request',
      listHeight: 'calc(100vh - 310px)',
      sparam: {
        ...this.sparam,
        page: 1,
        size: 30,
        interfaceType: '',
        chgStat: '',
        processStat: '',
        chgDate: [],
      },
      paging: {
        curPage: 1,
        totalCount: 1,
      },
      pageSizes: [15, 30, 50, 100],
      systemListShow: false,
    }
  },
  methods: {
    search () {
      const loading = this.$startLoading()
      console.log('search : ' + this.path, this.sparam)
      this.$http.get('/api/' + this.path, {
        params: this.sparam,
      }).then(response => {
        let pageList = response.data
        this.items = pageList.list
        this.paging = {
          curPage: pageList.curPage,
          totalCount: pageList.totalCount,
        }
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // Override search

    handlePageSizeChange (val) {
      this.sparam.size = val
      this.search()
    }, // handlePageSizeChange

    handlePageCurrentChange (val) {
      this.sparam.page = val
      this.search()
    }, // handlePageCurrentChange

    clickTransfer () {
      console.log('click transfer')
    }, // clickTransfer

    viewHistory (id) {
      console.log('view history', id)
    }, // viewHistory

    cbSystemRowClick (row) {

    }, // cbSystemRowClick

    chgStatStyle (val) {
      let style = 'color: #fff'
      if (val === '1') {
        style = 'color: #0000FF'
      } else if (val === '2') {
        style = 'color: #9900FF'
      } else if (val === '3') {
        style = 'color: #FF0000'
      } else {
        style = 'color: #990000'
      }
      return style
    }, // chgStatStyle
  },
  computed: {
    infTypes: function () {
      let kind = RuleUtil.CODEKEY.infType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    chgStats: function () {
      let kind = RuleUtil.CODEKEY.chgStat
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    procStats: function () {
      let kind = RuleUtil.CODEKEY.procStat
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
  },
}
</script>

<style scoped>
.advanced-search-bar {
  border: 1px solid #aab3b3;
  margin-top: 10px;
  background-color: #e6f7ff;
}
.advanced-search-bar .search-name {
  width: 180px;
}
.advanced-search-bar .search-id {
  width: 140px;
}
.advanced-search-bar .search-check {
  margin-left: 15px;
}
</style>

// react-front/src/component/rule/list/Request-list.jsx
import React from 'react'
import { Table, Pagination, Button, Checkbox } from 'antd'
import { Form, Input, Select, DatePicker } from 'antd'
import moment from 'moment'

import RuleList, { RuleSearch } from './RuleList'
import SubModal from '@/component/SubModal'
import RequestTransfer from './sub/RequestTransfer'
import SystemList from './System-list'
import BizList from '@/component/manage/list/BizCode-list'
import HistoryList from './RequestHistory-list'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class RequestSearch extends RuleSearch {
  state = {
    checked : true,
  }

  componentWillMount(){
    let auth = this.props.userInfo ? this.props.userInfo.auth : ''
    if(auth === '0' || auth === '5' || auth === '7' ){ // uncheck
       this.setState({
         checked: false,
       })
    } else if(auth === '6' || auth === '8' || auth === '9'){ //check 
      this.setState({
        checked: true,
      })
    }
  }

  onCheckAllChange = e => {
    this.setState({
      checkAll: e.target.checked,
    })
  }

  method = {
    ...this.method,

    clickTransfer: e => {
      this.refs.trnEdit.setState({visible: true})
    },

    setSystem: (type) => {
      let ref = this.refs.sysList
      let form = this.props.form
      
      let callback = (system) => {
        if (type === 'rcv') {
          form.setFieldsValue({rcvSystemId: system.id})
        } else if (type === 'send') {
          form.setFieldsValue({sendSystemId: system.id})
        }
        ref.setState({visible: false})
      }

      let childState = {
        list: {onDbClick: callback}
      }
      ref.setState({visible: true, childState: childState})
    },

    setBizCode: (type) => {
      let ref = this.refs.bizList
      let form = this.props.form
      
      let callback = (biz) => {
        if (type === 'rcv') {
          form.setFieldsValue({rcvJobCodeId: biz.id})
        } else if (type === 'send') {
          form.setFieldsValue({sendJobCodeId: biz.id})
        }
        ref.setState({visible: false})
      }

      let childState = {
        list: {onDbClick: callback}
      }
      ref.setState({visible: true, childState: childState})
    },

    renderOpts: (key) => {
      return urmsc.getSubListByKey(this.props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
  
  }

  render() {
    const { RangePicker } = DatePicker
    const { getFieldDecorator } = this.props.form

    return (
      <div className="advanced-search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.interfaceId']}>{getFieldDecorator("interfaceId")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.interfaceType']}>
              {getFieldDecorator("interfaceType", {initialValue: ""})(<Select size={"small"} className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("infType")}
              </Select>)}
            </Form.Item>
            <Form.Item label={locale['label.requestId']}>{getFieldDecorator("id")(<Input size="small"  className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.requestName']}>{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
          </div>
          <div className="row">
            <Form.Item label={locale['label.sourceSystem']}>
              {getFieldDecorator("sendSystemId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setSystem('send') }} />)}
            </Form.Item>
            <Form.Item label={locale['label.sndJobCode']}>
              {getFieldDecorator("sendJobCodeId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setBizCode('send') }} />)}
            </Form.Item>
            <Form.Item label={locale['label.changeStatus']}>
              {getFieldDecorator('chgStat', {initialValue: ""})(<Select size={"small"} className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("chgStat")}
              </Select>)}
            </Form.Item>
            <Form.Item label={locale['label.processStatus']}>
              {getFieldDecorator('processStat', {initialValue: ""})(<Select size={"small"} style={{width: "150px"}}>
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("procStat")}
              </Select>)}
            </Form.Item>
          </div>
          
          <div className="row">
            <Form.Item label={locale['label.targetSystem']}>
              {getFieldDecorator("rcvSystemId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setSystem('rcv') }} />)}
            </Form.Item>
            <Form.Item label={locale['label.rcvJobCode']}>
              {getFieldDecorator("rcvJobCodeId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setBizCode('rcv') }} />)}
            </Form.Item>
            <Form.Item label={locale['label.lastChangeDate']}>{getFieldDecorator("chgDate", {
              initialValue: [moment().subtract(1, 'y'), moment()]
            })(<RangePicker size="small" style={{width: "220px"}} />)}</Form.Item>

          <div className="test">
            <Form.Item label={locale['label.cbRegUser']}>{getFieldDecorator("cbRegUser",)(<Checkbox checked={this.state.checked} />)}</Form.Item>
            <Form.Item label={locale['label.cbSndUser']}>{getFieldDecorator("cbSndUser",)(<Checkbox checked={this.state.checked} />)}</Form.Item>
            <Form.Item label={locale['label.cbRcvUser']}>{getFieldDecorator("cbRcvUser",)(<Checkbox checked={this.state.checked} />)}</Form.Item>
          </div>

            <Form.Item className="search-buttons row">
              <Button icon="search" onClick={this.method.clickSearch} title={locale['label.search']} />
              <Button icon="plus" onClick={this.method.clickAdd} title={locale['label.add']} />
              <Button icon="switcher" onClick={this.method.clickTransfer} title="이관" />
              <Button icon="delete" onClick={this.method.clickDelete} title={locale['label.delete']} disabled={!this.props.canDelete()} />
            </Form.Item>
          </div>
        </Form>

        <SubModal ref="sysList" width="1110px">
          <SystemList key="list" path="system" codeList={this.props.codeList} onlySearch={true} />
        </SubModal>

        <SubModal ref="bizList" width="1215px">
          <BizList ref="list" onlySearch={true} />
        </SubModal>

        <SubModal ref="trnEdit" width="1215px">
          <RequestTransfer codeList={this.props.codeList} authList={this.props.authList} />
        </SubModal>
      </div>
    );
  }
}

class RequestList extends RuleList {
  constructor(props) {
    super(props)
    this.state.paging = {
      current: 1,
      size: 30,
      total: 1,
    }
  }
  
  method = {
    ...this.method,
    
    searchPage: (param, paging) => {
      if (!param) param = {}
      if (!paging) paging = this.state.paging
      
      /* parse moment for Date */
      for (let key in param) {
        if (key.endsWith('Date')) {
          let arr = [
            param[key][0].valueOf(),
            param[key][1].valueOf()
          ]
          param[key] = arr
        }
      }

      /* set page parameter */
      param = {
        ...param,
        page: paging.current,
        size: paging.size,
      }
      
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/' + this.props.path,
        data: param,
        success: function(res) {
          $this.setState({
            items: res.list,
            paging: {
              current: res.curPage,
              size: paging.size,
              total: res.totalCount,
            }
          })
        },
      })
    },
    
    handlePageChange: (page, size, form) => {
      let paging = {current: page, size: size}
      this.method.searchPage(form.getFieldsValue(), paging)
    },
    
    viewHistory: (reqId) => {
      let childState = {
        list: { scparam: {id: reqId} }
      }
      this.refs.hisList.setState({visible: true, childState: childState})
    }
  }
  
  pageSizes = ['30', '50', '100']

  render() {
    const { paging } = this.state
    let form = null

    return (
      <div className="urm-list">
        <WrappedRequestSearch {...this.props} search={this.method.searchPage} delete={this.method.clickDelete} canDelete={this.method.isPageDelete}
          wrappedComponentRef={ref => { if (ref) form = ref.props.form }} />
        <Table className="table-striped"
            dataSource={this.state.items} pagination={false} bordered
            size={"small"} scroll={{ x: 1400, y: 500 }} rowKey="id" rowSelection={this.rowSelection}>
          <Table.Column title={locale['label.id']} dataIndex="id" width="130px" />
          <Table.Column title={locale['label.name']} dataIndex="name" width="180px" />
          <Table.Column title={locale['label.interfaceType']} dataIndex="interfaceType" render={(val) => ( this.method.getTypeStr('infType', val) )} />
          <Table.Column title={locale['label.changeStatus']} dataIndex="chgStat" render={(val) =>  ( this.method.getTypeStr('chgStat', val) )} />
          <Table.Column title={locale['label.processStatus']} dataIndex="processStat" render={(val) => ( this.method.getTypeStr('procStat', val) )} />
          <Table.Column title={locale['label.interfaceId']} dataIndex="interfaceId" width="120px"/>
          <Table.Column title={locale['label.sourceMethod']} dataIndex="sendSystemType" width="100px" render={(val) => ( this.method.getTypeStr('sysType', val) )}/>
          <Table.Column title={locale['label.targetMethod']} dataIndex="rcvSystemType" width="100px" render={(val) => ( this.method.getTypeStr('sysType', val) )}/>
          <Table.Column title={locale['label.sourceSystem']} dataIndex="sendSystem.name" width="110px"/>
          <Table.Column title={locale['label.targetSystem']} dataIndex="rcvSystem.name" width="110px"/>
          <Table.Column title={locale['label.lastChangeDate']} dataIndex="chgDate" width="150px" render={(val) => ( moment(val).format('YYYY-MM-DD HH:mm') )}/>/>
          <Table.Column title="Operations" className="operations" width="120px" render={(val) =>
            (<div>
              <Button icon="edit" onClick={e => { this.method.clickEdit(val.id) }} title={locale['label.modify']} />
              <Button icon="delete" onClick={e => { this.method.clickDelete([val.id]) }} title={locale['label.delete']} disabled={!this.method.isPageDelete()} />
              <Button icon="history" onClick={e => { this.method.viewHistory([val.id]) }} title={locale['label.interfaceHistory']} />
            </div>)}
          />
        </Table>
        <Pagination defaultCurrent={paging.current} total={paging.total} className="urm-paging"
          showSizeChanger onShowSizeChange={(page, size) => { this.method.handlePageChange(page, size, form) }}
          pageSizeOptions={this.pageSize} defaultPageSize={paging.size} onChange={(page, size) => { this.method.handlePageChange(page, size, form) }}/>

        <SubModal ref="hisList" width="1200px">
          <HistoryList key="list" path="request/history" codeList={this.props.codeList} />
        </SubModal>
      </div>
    );
  }
}

const WrappedRequestSearch = Form.create({name:'request_search'})(RequestSearch)
export default RequestList
