// vue-front/src/components/statics/RequestChangeDay.vue
<template>
  <div class="urm-pannel">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item label="일자 선택">
          <el-date-picker v-model="procDate" type="daterange" value-format="yyyyMMdd" range-separator="~" style="width: 220px;"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
      </div>
    </div>
    <ChangeList ref="list" :items="listItem"/>
  </div>
</template>

<script>
import ChangeList from './list/RequestChangeList'

export default {
  computed: {
    procDate: {
      get: function () {
        return [this.sparam.startDate, this.sparam.endDate]
      },
      set: function (nVal) {
        this.sparam.startDate = nVal[0]
        this.sparam.endDate = nVal[1]
      }
    }
  },

  components: {
    ChangeList,
  },

  data () {
    return {
      path: '/api/stat/change/day',
      listItem: null,
      sparam: {
        type: '',
        startDate: '',
        endDate: '',
      },
    }
  },

  methods: {
    search() {
      const loading = this.$startLoading()
      this.$http.get(this.path, {
        params: this.sparams,
      }).then(response => {
        this.listItem = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(()=>{
        loading.close()
      })
    },
  }
}
</script>

// react-front/src/component/statics/RequestChangeDay.jsx
import React from 'react'
import { Form, DatePicker, Button } from 'antd'
import moment from 'moment'

import ChangeList from './list/RequestChange-list'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class DaySearch extends React.Component {
  componentDidMount() {
    this.props.search(this.props.form.getFieldsValue())
  }

  method = {
    clickSearch: e => {
      let form = this.props.form
      let dates = form.getFieldValue('processDate')
      let params = {
        startDate: dates[0].format('YYYYMMDD'),
        endDate: dates[1].format('YYYYMMDD'),
      }
      
      this.props.search(params)
    },
  }

  render() {
    const { RangePicker } = DatePicker
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label="일자 선택">{getFieldDecorator("processDate", {
              initialValue: [moment(), moment()]
            })(<RangePicker size="small" style={{width: "220px"}} allowClear={false} />)}</Form.Item>
            <Form.Item className="search-buttons">
              <Button icon="search" onClick={this.method.clickSearch} title={locale['label.search']} />
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

const WrappedDaySearch = Form.create({name:'cday_search'})(DaySearch)
export default class RequestChangeDay extends React.Component {
  method = {
    search: (params) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: '/URM/api/stat/change/day',
        data: params,
        success: function(res) {
          $this.refs.list.setState({items: res})
        }
      })
    }
  }

  codeList = () => {
    let codeList = this.props.commonCode
    return codeList ? codeList : []
  }

  render() {
    return (
      <div className="urm-panel">
        <WrappedDaySearch search={this.method.search} />
        <ChangeList ref="list" />
      </div>
    );
  }
}
