// react-front/src/component/manage/list/BizCode-list.jsx
import React, {useState} from 'react'
import { Table, Button } from 'antd'
import { Form, Input } from 'antd'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class BizSearch extends React.Component {
  componentDidMount() {
    this.props.search()
  }
  
  method = {
    clickSearch: e => {
      this.props.search(this.props.form.getFieldsValue())
    },
    
    clickAdd: e => {
      this.props.add()
    },

    renderButton: (render) => {
      return !this.props.onlySearch && render
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.bizNm']}>{getFieldDecorator("name")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.biz.level1.code']}>{getFieldDecorator("part1Id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.biz.level1.name']}>{getFieldDecorator("part1Name")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.biz.level2.code']}>{getFieldDecorator("part2Id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.biz.level2.name']}>{getFieldDecorator("part2Name")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item style={{marginLeft: "15px"}}>
              <Button icon="search" onClick={this.method.clickSearch} title={locale['label.search']} />
              {this.method.renderButton(
                <Button icon="plus" onClick={this.method.clickAdd} title={locale['label.add']} />
              )}
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

class BizList extends React.Component {
  state = {
    items: [],
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.items !== nextState.items) {
      return true
    }
    if (this.props.onDbClick !== nextProps.onDbClick) {
      return true
    }
    return false
  }

  method = {
    handleAdd: () => {
      let tmp = [...this.state.items]
      tmp.push({id: 'undefined-'+tmp.length})
      this.setState({items: tmp})
    },
    
    search: (param) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/code/business',
        data: param,
        success: function(list) {
          $this.setState({items: list})
        },
      })
    },

    updateList: (list) => {
      this.setState({items: list})
    },
  }

  render() {
    return (
      <div className="urm-list">
        <WrappedBizSearch {...this.props} search={this.method.search} add={this.method.handleAdd} />
        <EditableTable {...this.props} items={this.state.items} update={this.method.updateList} />
      </div>
    );
  }
}

BizList.defaultProps = {
  onlySearch: false
}

const EditableTable = Form.create({name:'editable_table'})((props) => {
  const { getFieldDecorator } = props.form
  const [editingKey, setEditingKey] = useState('')
  
  let method = {
    isEditing: record => record.id === editingKey,
    
    editableCell: (val, record, dataIndex) => {
      return ( method.isEditing(record) ?
        <Form.Item>{getFieldDecorator(dataIndex, {initialValue: val})(<Input size="small" />)}</Form.Item> : val
      );
    },

    clickEdit: (id) => {
      setEditingKey(id)
    },
    
    clickSave: (idx) => {
      let items = props.form.getFieldValue('items')
      let biz = {id: editingKey}
      /* set item*/
      if (props.items.length > idx) {
        biz = props.items[idx]
      }
      biz = { ...biz, ...items[idx]}
      
      /* validate */
      if (biz.id.startsWith('undefined')) {
        biz.id = ''
      }
      if (!biz.part1Id || biz.part1Id.trim().length === 0) {
        console.log('please input part1Id')
        return false
      }
      
      urmsc.ajax({
        type: 'POST',
        url: 'api/code/business',
        data: JSON.stringify(biz),
        contentType: 'application/json; charset=UTF-8',
        success: function(res) {
          props.update(res)
          setEditingKey('')
        }
      })
    },
    
    clickCancel: (id) => {
      setEditingKey('')
    },

    renderButton: (render) => {
      return !props.onlySearch && render
    },

    renderOperations: (val, record, idx) => {
      return ( method.isEditing(record) ? 
        <div>
          <Button icon="save" onClick={e => { method.clickSave(idx) }} title={locale['label.save']} />
          <Button icon="close" onClick={method.clickCancel} title={locale['label.cancel']} />
        </div>
         : <Button icon="edit" onClick={e => { method.clickEdit(record.id) }} title={locale['label.modify']} />
      );
    },
  }
  
  return (
    <Table className="table-striped" rowClassName="editable-row"
      dataSource={props.items} pagination={false} bordered
      size={"small"} scroll={{ y: 500 }} rowKey="id"
      onRow={(record, index) => {
        return {
          onDoubleClick: e => { if (props.onDbClick) props.onDbClick(record) }
        }
      }
    }>
      <Table.Column title={locale['label.bizId']} dataIndex="id" width="130px"/>
      <Table.Column title={locale['label.bizNm']} dataIndex="name" width="200px"
        render={(val, record, idx) => method.editableCell(val, record, 'items['+idx+'].name')}/>
      <Table.Column title={locale['label.biz.level1.code']} dataIndex="part1Id"
        render={(val, record, idx) => method.editableCell(val, record, 'items['+idx+'].part1Id')}/>
      <Table.Column title={locale['label.biz.level1.name']} dataIndex="part1Name"
        render={(val, record, idx) => method.editableCell(val, record, 'items['+idx+'].part1Name')}/>
      <Table.Column title={locale['label.biz.level2.code']} dataIndex="part2Id"
        render={(val, record, idx) => method.editableCell(val, record, 'items['+idx+'].part2Id')}/>
      <Table.Column title={locale['label.biz.level2.name']} dataIndex="part2Name"
        render={(val, record, idx) => method.editableCell(val, record, 'items['+idx+'].part2Name')}/>
      {method.renderButton(
        <Table.Column title="Operations" className="operations" width="90px"
          render={(val, record, idx) => (method.renderOperations(val, record, idx))} />
      )}
    </Table>
  );
})
const WrappedBizSearch = Form.create({name:'biz_search'})(BizSearch)
export default BizList

// vue-front/src/components/manage/list/BizCodeList.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.bizNm')">
          <el-input v-model="sparam.name" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.biz.level1.code')">
          <el-input v-model="sparam.part1Id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.biz.level1.name')">
          <el-input v-model="sparam.part1Name" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.biz.level2.code')">
          <el-input v-model="sparam.part2Id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.biz.level2.name')">
          <el-input v-model="sparam.part2Name" class="search-id" @change="search"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
        <el-button @click="clickEdit()" v-if="!onlySearch">{{$t('label.add')}}</el-button>
        <el-button @click="clickDelete('selected')" v-if="!onlySearch">{{$t('label.delete')}}</el-button>
      </div>
    </div>

    <el-table ref="table" :data="items" @row-dblclick="handleRowDblclick" :height="listHeight"
        border class="table-striped" :row-key="$randomRowKey" :cell-class-name="cellClass">
      <el-table-column type="selection" width="40" v-if="!onlySearch"/>
      <el-table-column :label="$t('label.bizId')" prop="id" width="130"/>
      <el-table-column :label="$t('label.bizNm')" width="200">
        <template slot-scope="scope">
          <span v-if="!scope.row.editable">{{scope.row.name}}</span>
          <el-input v-model="scope.row.name" v-if="scope.row.editable"/>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.biz.level1.code')">
        <template slot-scope="scope">
          <span v-if="!scope.row.editable">{{scope.row.part1Id}}</span>
          <el-input v-model="scope.row.part1Id" v-if="scope.row.editable"/>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.biz.level1.name')">
        <template slot-scope="scope">
          <span v-if="!scope.row.editable">{{scope.row.part1Name}}</span>
          <el-input v-model="scope.row.part1Name" v-if="scope.row.editable"/>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.biz.level2.code')">
        <template slot-scope="scope">
          <span v-if="!scope.row.editable">{{scope.row.part2Id}}</span>
          <el-input v-model="scope.row.part2Id" v-if="scope.row.editable"/>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.biz.level2.name')">
        <template slot-scope="scope">
          <span v-if="!scope.row.editable">{{scope.row.part2Name}}</span>
          <el-input v-model="scope.row.part2Name" v-if="scope.row.editable"/>
        </template>
      </el-table-column>
      <el-table-column width="85" class-name="edit-cell operations" v-if="!onlySearch">
        <template slot-scope="scope">
          <div v-if="!scope.row.editable">
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row)" plain/>
          </div>
          <div v-if="scope.row.editable">
            <el-button icon="el-icon-receiving" @click.stop="clickSave(scope.row)"/>
            <el-button icon="el-icon-close" @click.stop="clickCancel(scope.row)"/>
          </div>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
export default {
  props: {
    onlySearch: {
      type: Boolean,
      default: false,
    },
    items: {
      type: Array,
      default: function () {
        return []
      },
    },
  },
  data () {
    return {
      listHeight: 'calc(100vh - 175px)',
      sparam: {
        name: '',
        part1Id: '',
        part1Name: '',
        part2Id: '',
        part2Name: '',
      },
    }
  },
  methods: {
    search () {
      this.$emit('search', this.sparam)
    }, // search

    clickEdit (row) {
      if (row) {
        console.log('edit', row)
        row.editable ? (row.editable = true) : this.$set(row, 'editable', true)
      } else {
        this.items.push({
          editable: true,
          name: '',
          part1Id: '',
          part1Name: '',
          part2Id: '',
          part2Name: '',
        })
      }
    }, // clickEdit

    clickDelete (key) {
      let ids = []
      if (key === 'selected') {
        let checkedList = this.$refs.table.selection
        if (checkedList.length <= 0) {
          this.$message({message: this.$t('message.1004'), type: 'warning'})
          return
        }
        // TODO handle added item
      } else if (key.id) {
        ids.push(key.id)
      } else {
        this.items.some((it, idx) => {
          if (it.__randomKey__ == key.__randomKey__) {
            this.items.splice(idx, 1)
            return true
          }
        })
        return
      }
      let confirmProp = {
        confirmButtonText: 'YES',
        cancelButtonText: 'NO',
        closeOnClickModal: false,
        dangerouslyUseHTMLString: false,
        type: 'error',
      }
      this.$confirm('정말 삭제 하시겠습니까?', confirmProp).then(() => {
        const loading = this.$startLoading()
        this.$http({
          method : 'POST',
          url: '/api/code/business/delete',
          data: ids,
        }).then(response => {
          let res = response.data
          if (res.code === 0) {
            this.$message({message: 'delete ' + this.path.toUpperCase() + ' [ ' + res.obj + ' ]', type: 'success'})
            this.search()
          } else if (res.code === 1) {
            this.$message({message: '삭제 실패하였습니다. - ' + res.message + ' \n 영향도를 확인하여 주세요.', type: 'warning'})
          } else {
            this.$message({message: res.message, type: 'warning'})
          }
        }).catch(error => {
          this.$handleHttpError(error)
        }).finally(() => {
          loading.close()
        })
      }).catch(() => {})
    }, // clickDelete

    clickSave (row) {
      if (!row.part2Id || row.part2Id.trim().length === 0) {
        this.$message.warning('Level2 ID 를 입력하세요.')
        return false
      }
      if (!row.part2Name || row.part2Name.trim().length === 0) {
        this.$message.warning('Level2 명 을 입력하세요.')
        return false
      }

      console.log('save', row)
      const loading = this.$startLoading()
      this.$http({
        method : 'POST',
        url: '/api/code/business',
        data: row,
      }).then(() => {
        this.$message.success('저장 되었습니다.')
        this.search()
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // clickSave

    clickCancel (row) {
      row.editable = false
    }, // clickCancel

    handleRowDblclick (row) {
      this.$emit('row-dblclick', row)
    }, // handleRowDblclick

    cellClass (scope) {
      if (scope.row.editable && 1 < scope.columnIndex && scope.columnIndex < 7) {
        return 'edit-cell'
      }
    }, // cellClass
  },
  mounted () {
    if (!this.onlySearch) {
      this.search()
    }
  },
}
</script>
