// react-front/src/components/manage/list/User-list.jsx
import React from 'react'
import { Table, Button, Input, Form } from 'antd'

import BasicList, { BasicSearch } from '@/components/BasicList'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class UserSearch extends BasicSearch {
  componentDidMount() {
    this.props.search()
    
    let $el = document.querySelectorAll('.search-bar.' + this.props.path + ' input.ant-input')
    let _this = this
    $el.forEach((it) => {
      it.addEventListener('keydown', function(e) {
        if (e && e.keyCode === 13) {
          _this.props.search(_this.props.form.getFieldsValue())
        }
      })
    })
  }

  render() {
    const { getFieldDecorator } = this.props.form
    return (
      <div className={'search-bar ' + this.props.path}>
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.id']}>{getFieldDecorator("id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.name']} >{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
            <Form.Item label={locale['label.dept']}>{getFieldDecorator("dept")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item className="search-buttons row">
              <Button size="small" onClick={this.method.clickSearch}>{locale['label.search']}</Button>
              {this.method.renderButton(
                <div className="inline">
                  <Button size="small" onClick={this.method.clickAdd}>{locale['label.add']}</Button>
                  <Button size="small" type="danger" onClick={this.method.clickDelete} disabled={!this.props.canDelete()}>{locale['label.delete']}</Button>
                </div>
              )}
            </Form.Item>
          </div>
        </Form>
      </div>
    )
  }
}

class UserList extends BasicList {
  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.items !== nextState.items) {
      return true
    }
    if (this.props.authList && this.props.authList.length !== nextProps.authList.length) {
      return true
    }
    return false
  }

  method = {
    ...this.method,
    
    getAuthStr: (key) => {
      let obj = {}
      let list = this.props.authList
      for (let i = 0; i < list.length; i++) {
        let it = list[i]
        if (it.id === key) {
          obj = it
          break
        }
      }
      return obj.name
    },
  }

  render() {
    return (
      <div className="urm-list">
        <WrappedUserSearch {...this.props} search={this.method.search} delete={this.method.clickDelete} canDelete={this.method.isPageDelete} />
        <Table className="table-striped" dataSource={this.state.items} pagination={false}
            bordered size="small" scroll={{ x: 1200, /*y: 500*/ }} rowKey="id"
            rowSelection={this.rowSelection} onRow={this.onRow}>
          <Table.Column title={locale['label.id']} dataIndex="id" width="145px" />
          <Table.Column title={locale['label.name']} dataIndex="name" ellipsis />
          <Table.Column title={locale['label.dept']} dataIndex="deptName" />
          <Table.Column title={locale['label.position']} dataIndex="positionName" />
          <Table.Column title={locale['label.grade']} dataIndex="gradeName" />
          <Table.Column title={locale['label.generalTel']} dataIndex="generalTelNo" />
          <Table.Column title={locale['label.officeTel']} dataIndex="officeTelNo" />
          <Table.Column title={locale['label.mobile']} dataIndex="celNo" />
          <Table.Column title={locale['label.auth']} dataIndex="authId" width="155px" render={(val) => (this.method.getAuthStr(val))} />
          {this.method.renderButton(
            <Table.Column className="operations" width="85px" render={(val) =>
              (<div>
                <Button onClick={e => this.method.clickEdit(val.id)} icon="edit" />
                <Button icon="delete" type="danger" onClick={e => { this.method.clickDelete([val.id]) }} title={locale['label.delete']} disabled={!this.method.isPageDelete()} />
              </div>)}
            />
          )}
        </Table>
      </div>
    );
  }
}

const WrappedUserSearch = Form.create({ name: 'user_search' })(UserSearch)
export default UserList

// vue-front/src/components/manage/list/UserList.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.id')">
          <el-input v-model="sparam.id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.name')">
          <el-input v-model="sparam.name" class="search-name" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.dept')">
          <el-input v-model="sparam.deptName" class="search-id" @change="search"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
        <el-button @click="clickEdit()" v-if="!onlySearch">{{$t('label.add')}}</el-button>
        <el-button @click="clickDelete('selected')" type="danger" v-if="!onlySearch" plain>{{$t('label.delete')}}</el-button>
      </div>
    </div>

    <el-table ref="table" :data="items" @row-dblclick="handleRowDblclick" :height="listHeight" border class="table-striped">
      <el-table-column type="selection" width="40" v-if="!onlySearch"/>
      <el-table-column :label="$t('label.id')" prop="id" width="145"/>
      <el-table-column :label="$t('label.name')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.dept')" prop="deptName"/>
      <el-table-column :label="$t('label.position')" prop="positionName"/>
      <el-table-column :label="$t('label.grade')" prop="gradeName"/>
      <el-table-column :label="$t('label.generalTel')" prop="generalTelNo"/>
      <el-table-column :label="$t('label.officeTel')" prop="officeTelNo"/>
      <el-table-column :label="$t('label.auth')" width="170">
        <template slot-scope="scope">
          <span>{{getAuthStr(scope.row.authId)}}</span>
        </template>
      </el-table-column>
      <el-table-column width="85" class-name="edit-cell operations" v-if="!onlySearch">
        <template slot-scope="scope">
          <div>
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row.id)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row.id)" plain/>
          </div>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>
<script>
export default {
  props: {
    onlySearch: {
      type: Boolean,
      default: false,
    },
    items: {
      type: Array,
      default: function () {
        return []
      },
    },
  },
  data () {
    return {
      listHeight: 'calc(100vh - 165px)',
      path: 'user',
      sparam: {
        id: '',
        name: '',
        dept: '',
      },
    }
  },
  methods: {
    search () {
      this.$emit('search', this.sparam)
    }, // search

    clickEdit (id) {
      this.$emit('edit', id)
    }, // clickEdit

    clickDelete (key) {
      let ids = []
      if (key === 'selected') {
        ids = this.$refs.table.selection.map((it) => it.id)
        if (ids.length <= 0) {
          this.$message({message: this.$t('message.1004'), type: 'warning'})
          return
        }
      } else {
        ids.push(key)
      }
      let confirmProp = {
        confirmButtonText: 'YES',
        cancelButtonText: 'NO',
        closeOnClickModal: false,
        dangerouslyUseHTMLString: false,
        type: 'error',
      }
      this.$confirm('정말 삭제 하시겠습니까?', confirmProp).then(() => {
        const loading = this.$startLoading()
        this.$http({
          method : 'POST',
          url: '/api/' + this.path + '/delete',
          data: ids,
        }).then(response => {
          let res = response.data
          if (res.code === 0) {
            this.$message({message: 'delete user [ ' + res.obj + ' ]', type: 'success'})
            this.search()
          } else if (res.code === 1) {
            this.$message({message: '삭제 실패하였습니다. - ' + res.message + ' \n 영향도를 확인하여 주세요.', type: 'warning'})
          } else {
            this.$message({message: res.message, type: 'warning'})
          }
        }).catch(error => {
          this.$handleHttpError(error)
        }).finally(() => {
          loading.close()
        })
      }).catch(() => {})
    }, // clickDelete

    handleRowDblclick (row) {
      this.$emit('row-dblclick', row)
    }, // handleRowDblclick

    getAuthStr (key) {
      let auths = this.$store.state.auths
      let obj = {}
      auths.some((auth) => {
        if (auth.id === key) {
          obj = auth
          return true
        }
      })
      return obj.name
    }, // getAuthStr
  },
  mounted () {
    if (!this.items) {
      this.search()
    }
  }
}
</script>
