// vue-front/src/components/TopMenu.vue
<template>
  <div>
    <el-menu :default-active="activePage" mode="horizontal" @select="handleSelect">
      <el-menu-item index="main"><img src="@/assets/logo.gif"/></el-menu-item>
      <el-menu-item index="request">{{$t('urm.request')}}</el-menu-item>
      <el-menu-item index="data">{{$t('urm.data')}}</el-menu-item>
      <el-menu-item index="system">{{$t('urm.system')}}</el-menu-item>
      <el-submenu index="Manage">
        <template slot="title">{{$t('urm.manage')}}</template>
        <el-menu-item index="user">{{$t('urm.user')}}</el-menu-item>
      </el-submenu>
    </el-menu>
  </div>
</template>
<script>
export default {
  data () {
    return {
      activePage: 'main',
    }
  },

  methods: {
    handleSelect (key, keyPath) {
      console.log(key, keyPath)
      this.$router.push(key)
    }, // handleSelect
  }, // methods

  mounted () {
    let routePath = this.$route.path
    console.log('TopMenu mounted', routePath)
    if (routePath && routePath.length > 0) {
      this.activePage = routePath.substring(1)
      if (this.activePage === '')  {
        this.activePage = 'main'
      }
    } else {
      this.activePage = 'main'
    }
    console.log('mounted TopMenu')
  }, // mounted

  computed: {
    hasAuth: function () {
      return true
    }
  },
}
</script>

// react-front/src/component/TopMenu.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { Menu } from 'antd';

import logo from '../assets/logo.gif'

class TopMenu extends React.Component {
  constructor(props) {
    super(props)
    
    let pathname = window.location.pathname
    let pathArr = pathname.split('/')
    let last = pathArr[pathArr.length - 1]
    
    this.state = {
      current: last
    }
  }

  handleClick = e => {
    this.setState({
      current: e.key,
    })
  }

  render() {
    return (
      <div className="urm-menu">
        <div className="urm-logo">
          <img src={logo} alt="logo" height="29" />
          <span>EAI 요건 관리 시스템</span>
        </div>
        <Menu onClick={this.handleClick} selectedKeys={[this.state.current]} mode="horizontal">
          <Menu.Item key="request"><Link to="/URM/request">Request</Link></Menu.Item>
          <Menu.Item key="data"><Link to="/URM/data">Data</Link></Menu.Item>
          <Menu.Item key="system"><Link to="/URM/system">System</Link></Menu.Item>
          <Menu.SubMenu title={<span>Manage</span>}>
            <Menu.Item key="user"><Link to="/URM/user">User</Link></Menu.Item>
            <Menu.Item key="biz"><Link to="/URM/biz">Business Code</Link></Menu.Item>
          </Menu.SubMenu>
          <Menu.SubMenu title={<span>Result</span>}>
            <Menu.Item key="log"><Link to="/URM">Process Log</Link></Menu.Item>
            <Menu.Item key="stat"><Link to="/URM">Statics</Link></Menu.Item>
          </Menu.SubMenu>
          <Menu.SubMenu title={<span>SubMenu</span>}>
            <Menu.ItemGroup title="group1">
              <Menu.Item key="group1"><Link to="/URM">URM</Link></Menu.Item>
            </Menu.ItemGroup>
            <Menu.ItemGroup title="group2">
              <Menu.Item key="group2"><Link to="/URM">URM</Link></Menu.Item>
            </Menu.ItemGroup>
          </Menu.SubMenu>
        </Menu>
      </div>
    );
  }
}

export default TopMenu;
