// react-front/src/components/rule/editor/DataMap-editor.jsx
import React, { useState, useEffect } from 'react'
import { Button, Modal, Tree, message } from 'antd'
import { Form, Input } from 'antd'
import { Stage, Layer, Line } from 'react-konva'

import RuleEditor from './RuleEditor'
import SubModal from '@/components/SubModal'
import DataList from '@/components/rule/list/Data-list'
import DataEditor from './Data-editor'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale
const LIST_STATE = urmsc.LIST_STATE

class DataMap extends RuleEditor {
  state = {
    ...this.state,
    confirm: undefined
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.visible !== nextState.visible) {
      return true
    }
    if (JSON.stringify(this.state.item) !== JSON.stringify(nextState.item)) {
      return true
    }
    return false
  }

  childMethod = {
    ...this.childMethod,

    save: (saveItem) => {
      console.log(saveItem)
      if (!this.method.validator(saveItem)) {
        return false
      }
      
      let _this = this
      urmsc.ajax({
        type: 'POST',
        url: 'api/' + this.props.path,
        data: JSON.stringify(saveItem),
        contentType: 'application/json',
        success: function(res) {
          console.log(res)
          _this.setState({item: res})
          _this.state.confirm && _this.state.confirm(res.id)
          message.success(locale['message.0001'])
        },
        error: function(xhr) {
          message.warning('Update Fail. ' + xhr.statusText)
        }
      })
    },
  }
    

  render() {
    return (
      <Modal visible={this.state.visible} width="1040px" destroyOnClose
          footer={null} onCancel={this.method.handleCancel} className="urm-modal">
        <WrappedDataMapEditor codeList={this.props.codeList} userInfo={this.props.userInfo}
          item={this.state.item} {...this.childMethod} />
      </Modal>
    );
  }
}

const DataMapEditor = (props) => {
  const { form, item } = props
  const { getFieldDecorator } = form
  const { DirectoryTree, TreeNode } = Tree
  const [ lines, setLines ] = useState([])
  const [ values, setValues ] = useState([])
  const [ expandStatus, setExpandStatus ] = useState({ expanded: {src: true, tgt: true}, keys: {src: ['d-0'], tgt: ['d-0']} })

  useEffect(() => {
    props.setItem(form, item)
    setValues(item.mapValues ? item.mapValues : [])
    item.subRule = { mapLines: (item.mapLines ? item.mapLines : [])}
    method.setMapLines()
    console.log(lines)
    window.addEventListener('keydown', function(e) {
      let selected = item.subRule.selectedLine
      if (e.keyCode === 46 && selected) {
        let mapLines = item.subRule.mapLines
        for (let i = mapLines.length-1; i >= 0; i--) {
          let line = mapLines[i]
          if (line.sourceFieldId === selected.sId && line.targetFieldId === selected.tId) {
            mapLines.splice(i, 1)
          }
        }
        item.subRule.selectedLine = null
        method.setMapLines()
      }
    })
    // eslint-disable-next-line
  }, [item]); // Only re-run the effect if props.item changes

  useEffect(() => {
    let $el = document.querySelectorAll('.map-tree > .ant-tree')
    $el.forEach((it) => {
      it.onscroll = function(e) {
        method.setMapLines()
      }
    })
    method.setMapLines()
    // eslint-disable-next-line
  }, [expandStatus]); // Only re-run the effect if expandStatus changes

  let dataList = null
  let dataEdit = null
  let subRef = null

  let method = {
    clickSave: e => {
      item.subRule.mapValues = values
      let saveItem = method.makeMapObj()
      props.save(saveItem)
    },
    
    makeMapObj: () => {
      let saveItem = props.makeRuleObj(form, item);
      saveItem.mapLines = item.subRule.mapLines
      saveItem.mapValues = item.subRule.mapValues
      
      return saveItem
    },
    
    clearMapping: e => {
      item.subRule.mapLines = []
      setLines([])
    },
    
    setData: (type) => {
      let callback = (data) => {
        urmsc.ajax({
          type: 'GET',
          url: 'api/data/' + data.id,
          success: function(res) {
            let status = {...expandStatus}
            status.keys[type] = ['d-0']
            status.expanded[type] = true
            setExpandStatus(status)
            if (type === 'src') {
              item.sourceData = res
              form.setFieldsValue({sourceDataId: data.id})
            } else if (type === 'tgt') {
              item.targetData = res
              form.setFieldsValue({targetDataId: data.id})
            }
            item.subRule.mapLines = []
            setLines([])
          },
        })
        dataList.setState({visible: false})
      }
      
      let childState = {
        list: {onDbClick: callback, edit: method.editData(dataEdit)}
      }
      dataList.setState({visible: true, childState: childState})
    },
    
    getData: (type) => {
      let id = type === 'src' ? form.getFieldValue('sourceDataId') : form.getFieldValue('targetDataId')
      if (!id) return false
      
      urmsc.ajax({
        type: 'GET',
        url: 'api/data/' + id,
        success: function(res) {
          dataEdit.setState({visible: true, item: res})
        }
      })
    },
    
    editData: (editor) => (id) => {
      if (id) {
        urmsc.ajax({
          type: 'GET',
          url: 'api/data/' + id,
          success: function(res) {
            editor.setState({visible: true, item: res})
          }
        })
      } else {
        editor.setState({visible: true, item: {}})
      }
    },
    
    saveData: (data) => {
      urmsc.ajax({
        type: 'POST',
        url: 'api/data',
        data: JSON.stringify(data),
        contentType: 'application/json; charset=UTF-8',
        success: function(res) {
          console.log(res)
          dataEdit.setState({item: res})
          message.success(locale['message.0001'])
          
          subRef.method._updateItems(LIST_STATE.UPDATE, res)
          message.success(locale['message.0001'])
        },
        error: function(xhr) {
          message.warning('Update Fail. ' + xhr.statusText)
        }
      })
    },
    
    parseTreeData: (data) => {
      let treeData = []
      if (data) {
        let parent = {
          title: data.id,
          key: 'd-0',
          data: data,
        }
        parent.children = data.fields.map((field, idx) => {
          let title = <div className={"inline s-"+field.fieldId}>
            <div style={{width: 100}}>{field.engName}</div>
            <div style={{width: 150}}>{field.name}</div>
          </div>
          return {
            title: title,
            key: 'f-' + idx,
            data: field,
          }
        })
        treeData.push(parent)
      }
      return treeData
    },
    
    dropNode: (node, dragNode) => {
      if (!dragNode || !node.props.isLeaf) {
        return false
      }
      let _lines = item.subRule.mapLines
      let exist = false
      
      if (_lines && _lines.length > 0) {
        exist = (_lines.filter((it) => {
          return (it.sourceFieldId === dragNode.props.data.fieldId &&
            it.targetFieldId === node.props.data.fieldId)
        }).length > 0)
      }
      
      if (!exist) {
        _lines.push({
          sourceFieldId: dragNode.props.data.fieldId,
          targetFieldId: node.props.data.fieldId
        })
        console.log('push line', node)
      }
      item.subRule.mapLines = _lines
      
      method.setMapLines()
    },
    
    renderTreeNode: (type, treeData, isChild) => {
      return treeData.map((data, idx) => {
        let nodeProp = {
          key: data.key,
          title: data.title,
          data: data.data,
        }
        if (isChild) {
          let field = data.data
          nodeProp.isLeaf = true
          if (type === 'tgt') {
            nodeProp.title = (<div className={"inline t-"+field.fieldId} onClick={e => { method.editDefault(e, field) }}>
              <div key={0} style={{width: 100}}>{field.engName}</div>
              <div key={1} style={{width: 150}}>{field.name}</div>
              <div key={2} className="dVal">
                {method.renderDVal(field.fieldId)}
              </div>
            </div>)
          }
        }
        if (data.children && data.children.length) {
          return (
            <TreeNode {...nodeProp}>
              {method.renderTreeNode(type, data.children, true)}
            </TreeNode>
          );
        }
        return <TreeNode {...nodeProp} />
      })
    },
    
    renderDVal: (fieldId) => {
      let index = 0
      return values.filter((it, idx) => {
        index = idx
        return it.fieldId === fieldId
      }).map((it) => <span key={index} className="org">{it.defaultValue}</span>)
    },
    
    editDefault: (e, data) => {
      let $el = e.target
      let $p = document.querySelector('.edit')
      if ($p) {
        $p.classList.remove('edit')

        let $input = $p.querySelector('input')
        let val = $input.value
        method.saveDefault($input.dataset.fieldId, val)
        $p.removeChild($input)
        
        let $span = $p.querySelector('.org')
        if ($span) $span.classList.remove('hide')
      }
      
      if ($el.classList.contains('dVal') || $el.classList.contains('org')) {
        if ($el.classList.contains('org')) {
          $el = $el.parentNode
        }
        let isEdit = $el.classList.contains('edit')
        if (!isEdit) {
          $el.classList.add('edit')

          let $span = $el.querySelector('span.org')
          let val = ''
          if ($span) {
            val = $span.innerText
            $span.classList.add('hide')
          }
          let $input = document.createElement('input')
          $input.value = val
          $input.dataset.fieldId = data.fieldId
          $el.appendChild($input)
          $input.focus()
        }
      }
    },
    
    saveDefault: (fieldId, val) => {
      let tmp = [...values]
      for (let i = tmp.length-1; i >= 0; i--) {
        let it = tmp[i]
        if (it.fieldId === fieldId) {
          tmp.splice(i, 1)
          break
        }
      }
      
      if (val.trim().length > 0) {
        tmp.push({
          fieldId: fieldId,
          defaultValue: val
        })
      }
      setValues(tmp)
    },
    
    setMapLines: () => {
      let expanded = expandStatus.expanded
      if (item.subRule.mapLines) {
        let _lines = item.subRule.mapLines.map((it, idx) => {
          let $sP = document.querySelector('.map-tree.src > ul > li > span:first-child')
          let $tP = document.querySelector('.map-tree.tgt > ul > li > span:first-child')
          let $src = document.querySelector('.s-'+it.sourceFieldId)
          let $tgt = document.querySelector('.t-'+it.targetFieldId)
          
          let sPR = $sP.getBoundingClientRect()
          let tPR = $tP.getBoundingClientRect()
          let sR = expanded.src ? $src.getBoundingClientRect() : sPR
          let tR = expanded.tgt ? $tgt.getBoundingClientRect() : tPR
          
          return {sR: sR, tR: tR, sId: it.sourceFieldId, tId: it.targetFieldId}
        })
        setLines(_lines)
      }
    },
    
    drawLine: () => {
      let $canvas = document.querySelector('.line-canvas')
      if (!$canvas) return undefined
      let cR = $canvas.getBoundingClientRect()
      return lines.map((it, idx) => {
        let sR = it.sR
        let tR = it.tR
        let y1 = sR.top-cR.top+sR.height/2
        let y2 = tR.top-cR.top+tR.height/2
        
        let lineProps = {
          key: idx,
          stroke: '#0000ff',
          onMouseEnter: e => {
            let container = e.target.getStage().container()
            container.style.cursor = 'pointer'
          },
          onMouseLeave: e => {
            let container = e.target.getStage().container()
            container.style.cursor = 'default'
          },
          onClick: e => {
            if (y1 > 50 && y2 > 50)  method.selectLine(it, e)
          }
        }
        
        if (y1 < 34) {
          y1 = 34
          lineProps.stroke = '#00ffff'
        }
        if (y2 < 34) {
          y2 = 34
          lineProps.stroke = '#00ffff'
        }
        
        let selected = item.subRule ? item.subRule.selectedLine : undefined
        if (selected && selected.sId === it.sId && selected.tId === it.tId) {
          lineProps.stroke = '#ff0000'
        }
        
        let points = [0, y1, 200, y2]
        
        if (y1 !== y2) {
          points = [0, y1, 100, y1, 100, y2, 200, y2]
          lineProps.bezier = true
        }
        
        return <Line points={points} {...lineProps} />
      })
    },
    
    selectLine: (line, e) => {
      item.subRule.selectedLine = line
      method.setMapLines()
    },
    
    onExpand: (type, yn, keys) => {
      let status = {...expandStatus}
      status.keys[type] = keys
      status.expanded[type] = yn
      console.log(status)
      setExpandStatus(status)
    },
    
    setSelectNode: (node) => {
      console.log(node)
      if (!node.props.isLeaf) {
        let status = {...expandStatus}
        status.expanded.src = false
        setExpandStatus(status)
      }
      return node.props.isLeaf ? node : null
    },
    
    mappingName: () => {
      let _lines = item.subRule.mapLines
      let srcFlds = item.sourceData.fields
      let tgtFlds = item.targetData.fields
      
      tgtFlds.forEach((it) => {
        let src = srcFlds.filter((fld) => fld.engName === it.engName)
        let exist = false
        if (src.length > 0) {
          if (_lines && lines.length > 0) {
            exist = (_lines.filter((line) => {
              return (line.sourceFieldId === src[0].fieldId &&
                line.targetFieldId === it.fieldId)
            }).length > 0)
          }
          
          if (!exist) {
            _lines.push({
              sourceFieldId: src[0].fieldId,
              targetFieldId: it.fieldId
            })
          }
        }
      })
      item.subRule.mapLines = _lines
      method.setMapLines()
    },
  }

  let selectNode = null

  return (
    <div className="urm-editor">
      <div className="editor-buttons">
        <Button onClick={method.clickSave} disabled={!props.isPageSave()}>{locale['label.save']}</Button>
      </div>
      <Form colon={false}>
        <div className="row">
          <Form.Item label={locale['label.dataMapId']}>{getFieldDecorator("id")(<Input size="small" className="size-id" readOnly />)}</Form.Item>
          <Form.Item label={locale['label.dataMapName']}>{getFieldDecorator("name")(<Input size="small" className="size-name" />)}</Form.Item>
        </div>
        
        <hr />
        
        <div className="row">
          <div className="col-2">
            <Form.Item label={locale['label.outData']} className="data-id">
              {getFieldDecorator("sourceDataId")(<Input.Search size="small" className="size-id" readOnly
                onClick={e => { method.getData('src') }} onSearch={vars => { method.setData('src') }} />)}
            </Form.Item>
          </div>
          <div className="center" style={{width: 200}}>
            <Button icon="link" onClick={method.mappingName} title={locale['label.connectName']} />
            <Button icon="disconnect" onClick={method.clearMapping} title={locale['label.deleteMapping']} />
          </div>
          <div className="col-3 row">
            <Form.Item label={locale['label.inData']} className="data-id">
              {getFieldDecorator("targetDataId")(<Input.Search size="small" className="size-id" readOnly
                onClick={e => { method.getData('tgt') }} onSearch={vars => { method.setData('tgt') }} />)}
            </Form.Item>
          </div>
        </div>
        <div className="row">
          <div className="map-tree src">
            <div className="row">
              <div className="col-1 title">{locale['label.map.item1']}</div>
              <div className="col-1 title">{locale['label.map.item2']}</div>
            </div>
            <DirectoryTree draggable expandedKeys={expandStatus.keys.src}
                onDragStart={info => { selectNode = method.setSelectNode(info.node) }}
                onExpand={(expandedKeys, {expanded, node}) => { method.onExpand('src', expanded, expandedKeys) }}>
              {method.renderTreeNode('src', method.parseTreeData(item.sourceData))}
            </DirectoryTree>
          </div>
          <Stage className="line-canvas" width={200} height={584}>
            <Layer>
              {method.drawLine()}
            </Layer>
          </Stage>
          <div className="map-tree tgt">
            <div className="row">
              <div className="col-1 title">{locale['label.map.item1']}</div>
              <div className="col-1 title">{locale['label.map.item2']}</div>
              <div className="col-1 title">{locale['label.map.defaultVal']}</div>
            </div>
            <DirectoryTree draggable expandedKeys={expandStatus.keys.tgt}
                onDrop={info => { method.dropNode(info.node, selectNode) }}
                onExpand={(expandedKeys, {expanded, node}) => { method.onExpand('tgt', expanded, expandedKeys) }}>
              {method.renderTreeNode('tgt', method.parseTreeData(item.targetData))}
            </DirectoryTree>
          </div>
        </div>
      </Form>
      
      <SubModal ref={(list) => { dataList = list }} width="980px" bodyStyle={{maxHeight: 600, overflow: 'auto'}}>
        <DataList key="list" ref={(list) => { subRef = list }} path="data" userInfo={props.userInfo} codeList={props.codeList} />
      </SubModal>
      
      <DataEditor ref={(edit) => { dataEdit = edit }} path="data" userInfo={props.userInfo}
        codeList={props.codeList} save={method.saveData} />
    </div>
  );
}

const WrappedDataMapEditor = Form.create({name:'datamap_editor'})(DataMapEditor)
export default DataMap

// vue-front/src/components/rule/editor/request/DataMapEditor.vue
<template>
  <div class="urm-editor">
    <div class="editor-buttons">
      <el-button @click="clickSave" plain>{{$t('label.save')}}</el-button>
    </div>
    <el-form label-width="135px" :inline="true">
      <el-form-item :label="$t('label.dataMapId')">
        <el-input v-model="item.id" class="size-id" disabled/>
      </el-form-item>
      <el-form-item :label="$t('label.dataMapName')">
        <el-input v-model="item.name" class="size-name"/>
      </el-form-item>
    </el-form>
    
    <hr/>
    <div class="map-view">
      <div class="map-header">
        <div class="el-form-item el-form-item--small src">
          <label class="el-form-item__label">{{$t('label.outData')}}</label>
          <el-input v-model="item.sourceDataId" class="size-id" @click.native.prevent="showDataEditor('src')" readonly>
            <el-button slot="append" icon="el-icon-search" @click.stop="showDataList('src')"/>
          </el-input>
        </div>
        <div class="mapping-buttons">
          <el-tooltip :content="$t('label.deleteMapping')" placement="top" :open-delay="500" :enterable="false">
            <el-button @click="clearMapping"><i class="el-icon-brush" style="transform: rotate(195deg);"/></el-button>
          </el-tooltip>
          <el-tooltip :content="$t('label.connectName')" placement="top" :open-delay="500" :enterable="false">
            <el-button icon="el-icon-link" @click="mappingByName"/>
          </el-tooltip>
        </div>
        <div class="el-form-item el-form-item--small tgt">
          <label class="el-form-item__label">{{$t('label.inData')}}</label>
          <el-input v-model="item.targetDataId" class="size-id" @click.native.prevent="showDataEditor('tgt')" readonly>
            <el-button slot="append" icon="el-icon-search" @click.stop="showDataList('tgt')"/>
          </el-input>
        </div>
      </div>
      <div class="map-tree">
        <div class="src">
          <div class="map-tree-header">
            <div style="width: 160px;">{{$t('label.map.item1')}}</div>
            <div style="width: 155px;">{{$t('label.map.item2')}}</div>
          </div>
          <el-tree ref="srcDataTree" class="src-data-view" :data="srcTreeData" :props="treeProps" node-key="id" :render-content="renderData"
            @scroll.native="throttleUpdateMapping"
            :render-after-expand="false" :expand-on-click-node="false" default-expand-all :indent="12"/>
        </div><!--
     --><div ref="mapCanvas" class="mapping-canvas" @keyup.delete="deleteLine" tabindex="999"/><!-- 
     --><div class="tgt">
          <div class="map-tree-header">
            <div style="width: 160px;">{{$t('label.map.item1')}}</div>
            <div style="width: 160px;">{{$t('label.map.item2')}}</div>
            <div style="width: 165px;">{{$t('label.map.defaultVal')}}</div>
          </div>
          <el-tree ref="tgtDataTree" class="tgt-data-view" :data="tgtTreeData" :props="treeProps" node-key="id" :render-content="renderData"
            @scroll.native="throttleUpdateMapping" @node-click="handleNodeClick"
            :render-after-expand="false" :expand-on-click-node="false" default-expand-all :indent="12"/>
        </div>
      </div>
    </div>

    <el-dialog :visible.sync="dataListShow" width="980px" top="5vh" append-to-body :close-on-click-modal="false">
      <DataList ref="dataList" :items="datas"
        @search="searchDataList" @edit="editData" @row-dblclick="cbDataRowClick"/>
    </el-dialog>

    <el-dialog :visible.sync="dataEditorShow" width="1080px" top="8vh" append-to-body :close-on-click-modal="false">
      <DataEditor :item="data" @save="saveData"/>
    </el-dialog>
  </div>
</template>
<script>
import _ from 'lodash'
import Raphael from 'raphael'

import RuleEditor from '@/components/rule/editor/RuleEditor'

import DataEditor from '@/components/rule/editor/DataEditor'
import DataList from '@/components/rule/list/DataList'

const NOR_COLOR = '#0000FF'
const BLUR_COLOR = '#00FFFF'
const SEL_COLOR = '#FF0000'

export default {
  mixins: [RuleEditor],
  components: {
    DataList,
    DataEditor,
  },

  data () {
    return {
      tgtType: '',
      dataListShow: false,
      datas: null,
      dataEditorShow: false,
      data: null,
      treeProps: {
        children: 'children',
        label: 'label',
      },

      dragNodeId: null,
    }
  },

  methods: {
    showDataList (type) {
      this.tgtType = type
      if (!this.datas) {
        this.searchDataList(() => {
          this.dataListShow = true
        })
      } else {
        this.dataListShow = true
      }
    }, // showDataList

    searchDataList (cbFunc) {
      let sparam = this.$refs.dataList ? this.$refs.dataList.sparam : {}
      const loading = this.$startLoading()
      this.$http.get('/api/data', {
        params: sparam,
      }).then(response => {
        this.datas = response.data
        typeof cbFunc === 'function' && cbFunc()
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // searchDataList

    cbDataRowClick (row) {
      this.$http.get('/api/data/' + row.id, {
      }).then(response => {
        let data = response.data
        if (this.tgtType === 'src') {
          this.item.sourceDataId = data.id
          this.item.sourceData = data
        } else if (this.tgtType === 'tgt') {
          this.item.targetDataId = data.id
          this.item.targetData = data
        }
        this.item.mapLines = []
        this.$nextTick(() => {
          this.updateMappingLines()
        })
        this.dataListShow = false
      })
    }, // cbDataRowClick

    showDataEditor (type) {
      this.tgtType = type
      if (type === 'src') {
        this.editData(this.item.sourceDataId)
      } else if (type === 'tgt') {
        this.editData(this.item.targetDataId)
      }
    }, // showDataEditor

    editData (id) {
      let newItem = { id: '', fields: [] }
      if (id) {
        console.log('edit data : ' + id)
        this.$http.get('/api/data/' + id, {
        }).then(response => {
          this.data = response.data
          if (!this.data.fields) {
            this.data.fields = newItem.fields
          }
          this.dataEditorShow = true
        })
      } else {
        this.data = newItem
        this.dataEditorShow = true
      }
    }, // editData

    saveData (data) {
      console.log('save data', data)
      this.$http({
        method : 'POST',
        url: '/api/data',
        data: data,
      }).then(response => {
        this.$message({message: this.$t('message.0001'), type: 'success'})
        data.id = response.data.id
        this.updateItem(data)
      }).catch(error => {
        this.$handleHttpError(error)
      })
    }, // saveData

    updateItem (item) {
      let org = this.item
      let tgt = this.tgtType
      if (tgt === 'src' && (!org.sourceDataId || org.sourceDataId.length === 0)) {
        org.sourceDataId = item.id
      } else if (tgt === 'tgt' && (!org.targetDataId || org.targetDataId.length === 0)) {
        org.targetDataId = item.id
      }
      this.searchDataList()
    }, // updateItem

    convertTreeData (data, type) {
      let tree = []
      if (data && data.id) {
        let rootData = {type: 'data', id: type + '-data', label: data.id}
        if (data.fields && data.fields.length > 0) {
          let treeData = []
          data.fields.forEach((f) => {
            let tId = type + '-' + f.fieldId
            let child = {type: 'field', id: tId, fId: f.fieldId, field: f, isEdit: false}
            this.item.mapValues.some((v) => {
              if (v.fieldId === data.fId) {
                child.value = v.defaultValue
              }
            })
            treeData.push(child)
          })
          rootData.children = treeData
        }
        tree.push(rootData)
      }
      return tree
    }, // convertTreeData

    renderData (h, tree) {
      let data = tree.data
      let icon = ''
      if (data.type === 'field') {
        icon = 'el-icon-tickets'
      } else {
        icon = 'el-icon-folder'
      }
      const iEl = (<i style="line-height: 18px; width: 18px;" class={icon}/>)
      if (data.type === 'field') {
        let f = data.field
        if (data.id.startsWith('s')) { // source
          let labelEl1 = (<span style="width: 109px;" class="nowarp">{f.engName}</span>)
          let labelEl2 = (<span style="width: 141px;" class="nowarp">{f.name}</span>)
          return (
            <span id={data.id} class="nowarp" style="width: 100%; height: 22px; display: flex;" draggable="true"
                on-dragstart={(ev) => this.dragStart(ev)}
                on-dragend={(ev) => this.dragEnd(ev)}>
              {iEl}{labelEl1}{labelEl2}
            </span>
          )
        } else { // target
          let labelEl1 = (<span style="width: 112px;" class="nowarp">{f.engName}</span>)
          let labelEl2 = (<span style="width: 161px;" class="nowarp">{f.name}</span>)
          let labelEl3 = (
            <span style="width: 144px;" class="nowarp" on-click={(ev) => this.clickValueData(ev, data)}>
              <span v-show={!data.isEdit}>{data.value}</span>
              <span v-show={data.isEdit}>
                <el-input v-model={data.value} class="tree-node-input"
                  nativeOnFocusout={() => this.changeValueData(data)}/>
              </span>
            </span>
          )
          return (
            <span id={data.id} class="nowarp droppable" style="width: 100%; height: 22px; display: flex;"
                on-dragover={(ev) => this.dragOver(ev)}
                on-dragleave={(ev) => this.dragLeave(ev)}
                on-dragenter={(ev) => this.dragEnter(ev)}
                on-drop={(ev) => this.drop(ev)}>
              {iEl}{labelEl1}{labelEl2}{labelEl3}
            </span>
          )
        }
      } else {
        let labelEl = (<span class="nowarp">{data.label}</span>)
        return (
          <span id={data.id} class="nowarp droppable" style="width: 100%; display: flex;">
            {iEl}{labelEl}
          </span>
        )
      }
    }, // renderData

    dragStart (ev) {
      console.log('dragStart')
      this.dragNodeId = ev.target.id
      ev.dataTransfer.setData('text', this.dragNodeId)
      ev.target.style.color = '#409EFF'
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = '#ffffd0'
    }, // dragStart

    dragEnd (ev) {
      console.log('dragEnd')
      ev.preventDefault()
      ev.target.style.color = ''
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = ''
      this.dragNodeId = null
    }, // dragEnd

    dragEnter (ev) {
      let dropNodeId = ev.target.id
      !dropNodeId && (dropNodeId = ev.target.closest('span.droppable').id)
      let sData = this.$refs.srcDataTree.getNode(this.dragNodeId).data
      let tData = this.$refs.tgtDataTree.getNode(dropNodeId).data
      let droppable = (sData.type === 'field' && tData.type === 'field') ? true : false
      if (!droppable) {
        return
      }
      ev.preventDefault()
      ev.stopPropagation()
      ev.target.style.color = '#409EFF'
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = '#ffffd0'
    }, // dragEnter

    dragOver (ev) {
      let dropNodeId = ev.target.id
      !dropNodeId && (dropNodeId = ev.target.closest('span.droppable').id)
      let sData = this.$refs.srcDataTree.getNode(this.dragNodeId).data
      let tData = this.$refs.tgtDataTree.getNode(dropNodeId).data
      let droppable = (sData.type === 'field' && tData.type === 'field') ? true : false
      if (!droppable) {
        return
      }
      ev.preventDefault()
      ev.stopPropagation()
      ev.target.style.color = '#409EFF'
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = '#ffffd0'
    }, // dragOver

    dragLeave (ev) {
      ev.preventDefault()
      ev.stopPropagation()
      ev.target.style.color = ''
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = ''
    }, // dragLeave

    drop (ev) {
      ev.preventDefault()
      ev.stopPropagation()
      ev.target.style.color = ''
      ev.target.closest('div.el-tree-node__content').style.backgroundColor = ''

      let dragNodeId = ev.dataTransfer.getData('text')
      let dropNodeId = ev.target.id
      !dropNodeId && (dropNodeId = ev.target.closest('span.droppable').id)
      let sData = this.$refs.srcDataTree.getNode(dragNodeId).data
      let tData = this.$refs.tgtDataTree.getNode(dropNodeId).data
      let isOk = this.addMappingData(sData, tData)
      if (isOk) {
        this.drawMappingLine(dragNodeId, dropNodeId)
      }
    }, // drop

    clickValueData (ev, data) {
      ev.stopPropagation()
      data.isEdit = true
      this.$nextTick(() => {
        this.$refs.tgtDataTree.$el.querySelector('#' + data.id + ' input').focus()
      })
    }, // clickValueData

    changeValueData (data) {
      console.log('in')
      this.item.mapValues.some((v) => {
        if (v.fieldId === data.fId) {
          v.defaultValue = data.value
        }
      })
      data.isEdit = false
    }, // changeValueData

    addMappingData(sData, tData) {
      console.log('addMappingData', sData, tData)
      let isOk = false
      let isExist = false
      this.item.mapLines.some((line) => {
        if (line.sourceFieldId === sData.fId && line.targetFieldId === tData.fId) {
          isExist = true
        }
        if (isExist) {
          return true // break
        }
      })
      if (isExist) {
        let mapping = sData.fId + ' to ' + tData.fId
        this.$message({type: 'warning', message: 'already exist mapping [' + mapping + ']'})
        isOk = false
      } else {
        this.item.mapLines.push({ sourceFieldId: sData.fId, targetFieldId: tData.fId })
        isOk = true
      }
      return isOk
    }, // addMappingData

    handleNodeClick (data) {
      console.log('handleNodeClick', data)
      this.selectedNode = data
    }, // handleNodeClick

    mappingByName () {
      let lines = this.item.mapLines
      let srcFlds = this.item.sourceData.fields
      let tgtFlds = this.item.targetData.fields
      
      tgtFlds.forEach((tFld) => {
        let src = srcFlds.find((sFld) => (sFld.engName === tFld.engName))
        let filteredLines = []
        if (src) {
          if (lines && lines.length > 0) {
            filteredLines = lines.filter((line) =>
              (line.sourceFieldId === src.fieldId && line.targetFieldId === tFld.fieldId))
          }
          
          if (filteredLines.length === 0) {
            lines.push({
              sourceFieldId: src.fieldId,
              targetFieldId: tFld.fieldId
            })
          }
        }
      })
      this.updateMappingLines()
    }, // mappingByName

    clearMapping () {
      let confirmProp = {
        confirmButtonText: 'YES',
        cancelButtonText: 'NO',
        closeOnClickModal: false,
        dangerouslyUseHTMLString: false,
        type: 'error',
      }
      this.$confirm('매핑을 전부 삭제하시겠습니까?', confirmProp).then(() => {
        this.item.mapLines = []
        this.mapPaper.clear()
      }).catch(() => {})
    }, // clearMapping

    updateMappingLines () {
      let newDiv = document.createElement('div')
      let newPaper = Raphael(newDiv, 200, 555)
      this.item.mapLines.forEach((line) => {
        let tgtNodeId = 't-' + line.targetFieldId
        try {
          let srcNodeId = 's-' + line.sourceFieldId
          this.drawMappingLine(srcNodeId, tgtNodeId, newPaper)
        } catch (err) {
          console.error(err)
        }
      })
      this.mapPaper && this.mapPaper.clear()
      let mapCanvas = this.$refs.mapCanvas
      while (mapCanvas.hasChildNodes()) {
        mapCanvas.removeChild(mapCanvas.firstChild)
      }
      mapCanvas.appendChild(newDiv.firstChild)
      this.mapPaper = newPaper
    }, // updateMappingLines

    drawMappingLine (srcNodeId, tgtNodeId, paper) {
      !paper && (paper = this.mapPaper)
      const canvasY = this.getElTop(this.$refs.mapCanvas)
      let srcDataTree = this.$refs.srcDataTree
      let tgtDataTree = this.$refs.tgtDataTree
      let srcNode = srcDataTree.getNode(srcNodeId)
      let tgtNode = tgtDataTree.getNode(tgtNodeId)
      let srcNodeEl = srcDataTree.$el.querySelector('#' + srcNodeId)
      let tgtNodeEl = tgtDataTree.$el.querySelector('#' + tgtNodeId)
      if (!srcNodeEl || !tgtNodeEl) {
        return
      }
      let sInfo = this.getLineInfo(srcDataTree, srcNode, srcNodeEl, canvasY)
      let tInfo = this.getLineInfo(tgtDataTree, tgtNode, tgtNodeEl, canvasY)

      let centerY = sInfo.y + ((tInfo.y - sInfo.y) / 2)
      let pathStr = 'M0,' + sInfo.y + ' Q50,' + sInfo.y + ',100,' + centerY + ' Q150,' + tInfo.y + ',200,' + tInfo.y
      let line = paper.path(pathStr)
      let lineColor = (sInfo.isBlur || tInfo.isBlur) ? BLUR_COLOR : NOR_COLOR
      line.attr({'stroke': lineColor, 'stroke-width': 3})
      line.node.style.cursor = 'pointer'

      line.linedata = {target: tgtNode.data, source: srcNode.data}
      line.selected = false
      line.click(function () {
        if (this.attr('stroke') === BLUR_COLOR) {
          return
        }
        this.selected ? this.attr({'stroke': lineColor}) : this.attr({'stroke': SEL_COLOR})
        this.selected = !this.selected
      })
    }, // drawMappingLine

    throttleUpdateMapping: _.throttle(function () {
      this.updateMappingLines()
    }, 100), // handleTreeScroll

    deleteLine () {
      let delItems = []
      this.mapPaper.forEach((el) => {
        el.selected && delItems.push(el)
      })
      while (delItems.length > 0) {
        let item = delItems.shift()
        let sData = item.linedata.source, tData = item.linedata.target
        item.remove() // delete line
        this.item.mapLines.some((line, idx) => {
          if (line.sourceFieldId === sData.fId && line.targetFieldId === tData.fId) {
            this.item.mapLines.splice(idx, 1)
            return true
          }
        })
      }
    }, // deleteLine

    getElTop (el) {
      let box = el.getBoundingClientRect()
      let body = document.body
      let docEl = document.documentElement
      let scrollTop = window.pageYOffset || docEl.scrollTop || body.scrollTop
      let clientTop = docEl.clientTop || body.clientTop || 0
      let top  = box.top +  scrollTop - clientTop
      return Math.round(top)
    }, // getElTop

    getLineInfo (dataTree, node, nodeEl, canvasY) {
      let isBlur = false
      while (node) {
        if (nodeEl.offsetHeight !== 0 || nodeEl.offsetWidth !== 0) {
          break
        }
        node = node.parent
        nodeEl = dataTree.$el.querySelector('#' + node.key)
        isBlur = true
        if (!nodeEl) {
          console.error('does not exist node element - ' + node.key)
          break
        }
      }
      let y = this.getElTop(nodeEl) - canvasY + 8
      if (y < 0 || y > 600) {
        y = y < 0 ? 0 : 600
        isBlur = true
      }
      return {y: y, isBlur: isBlur}
    }, // getLineInfo

    customValidator () {
      let item = this.item
      if (!item.sourceDataId || item.sourceDataId.length === 0) {
        this.$message({type: 'error', message: 'please add fields'})
        return false
      }
      if (!item.targetDataId || item.targetDataId.length === 0) {
        this.$message({type: 'error', message: 'please add fields'})
        return false
      }
      return true
    }, // customValidator
  }, // methods

  computed: {
    srcTreeData () {
      return this.convertTreeData(this.item.sourceData, 's')
    },
    tgtTreeData () {
      return this.convertTreeData(this.item.targetData, 't')
    },
  },
}
</script>
<style scoped>
div.map-view .src {
  width: 315px;
}
div.map-view .tgt {
  width: 485px;
}

div.map-header, div.map-tree, div.map-tree-header {
  display: flex;
}
div.map-header .mapping-buttons {
  width: 200px;
  text-align: center;
}
div.map-header .mapping-buttons .el-button--small {
  margin: 0;
}

div.map-tree .src, div.map-tree .tgt {
  border: 1px solid #DCDFE6;
}
div.map-tree .src-data-view, div.map-tree .tgt-data-view {
  height: 555px;
  overflow-y: auto;
  font-size: 14px;
}
div.map-tree .mapping-canvas {
  margin-top: 28px;
  width: 200px;
  height: 555px;
}
div.map-tree .mapping-canvas:focus {
  outline: none;
}

div.map-tree-header > div {
  border-bottom: 1px solid #DCDFE6;
  background-color: #F5F7FA;
  padding: 3px 10px 5px;
}
div.map-tree-header > div:not(:last-child) {
  border-right: 1px solid #DCDFE6;
}
</style>
