// vue-front/src/components/manage/list/UserList.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.id')">
          <el-input v-model="sparam.id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.name')">
          <el-input v-model="sparam.name" class="search-name" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.dept')">
          <el-input v-model="sparam.deptName" class="search-id" @change="search"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
        <el-button @click="clickEdit()" v-if="!onlySearch">{{$t('label.add')}}</el-button>
        <el-button @click="clickDelete('selected')" type="danger" v-if="!onlySearch" plain>{{$t('label.delete')}}</el-button>
      </div>
    </div>

    <el-table ref="table" :data="items" @row-dblclick="handleRowDblclick" :height="listHeight" border class="table-striped">
      <el-table-column type="selection" width="40" v-if="!onlySearch"/>
      <el-table-column :label="$t('label.id')" prop="id" width="145"/>
      <el-table-column :label="$t('label.name')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.dept')" prop="deptName"/>
      <el-table-column :label="$t('label.position')" prop="positionName"/>
      <el-table-column :label="$t('label.grade')" prop="gradeName"/>
      <el-table-column :label="$t('label.generalTel')" prop="generalTelNo"/>
      <el-table-column :label="$t('label.officeTel')" prop="officeTelNo"/>
      <el-table-column :label="$t('label.auth')" width="170">
        <template slot-scope="scope">
          <span>{{getAuthStr(scope.row.authId)}}</span>
        </template>
      </el-table-column>
      <el-table-column width="85" class-name="edit-cell operations" v-if="!onlySearch">
        <template slot-scope="scope">
          <div>
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row.id)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row.id)" plain/>
          </div>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>
<script>
export default {
  props: {
    onlySearch: {
      type: Boolean,
      default: false,
    },
    items: {
      type: Array,
      default: function () {
        return []
      },
    },
  },
  data () {
    return {
      listHeight: 'calc(100vh - 165px)',
      path: 'user',
      sparam: {
        id: '',
        name: '',
        dept: '',
      },
    }
  },
  methods: {
    search () {
      this.$emit('search', this.sparam)
    }, // search

    clickEdit (id) {
      this.$emit('edit', id)
    }, // clickEdit

    clickDelete (key) {
      let ids = []
      if (key === 'selected') {
        ids = this.$refs.table.selection.map((it) => it.id)
        if (ids.length <= 0) {
          this.$message({message: this.$t('message.1004'), type: 'warning'})
          return
        }
      } else {
        ids.push(key)
      }
      let confirmProp = {
        confirmButtonText: 'YES',
        cancelButtonText: 'NO',
        closeOnClickModal: false,
        dangerouslyUseHTMLString: false,
        type: 'error',
      }
      this.$confirm('정말 삭제 하시겠습니까?', confirmProp).then(() => {
        const loading = this.$startLoading()
        this.$http({
          method : 'POST',
          url: '/api/' + this.path + '/delete',
          data: ids,
        }).then(response => {
          let res = response.data
          if (res.code === 0) {
            this.$message({message: 'delete user [ ' + res.obj + ' ]', type: 'success'})
            this.search()
          } else if (res.code === 1) {
            this.$message({message: '삭제 실패하였습니다. - ' + res.message + ' \n 영향도를 확인하여 주세요.', type: 'warning'})
          } else {
            this.$message({message: res.message, type: 'warning'})
          }
        }).catch(error => {
          this.$handleHttpError(error)
        }).finally(() => {
          loading.close()
        })
      }).catch(() => {})
    }, // clickDelete

    handleRowDblclick (row) {
      this.$emit('row-dblclick', row)
    }, // handleRowDblclick

    getAuthStr (key) {
      let auths = this.$store.state.auths
      let obj = {}
      auths.some((auth) => {
        if (auth.id === key) {
          obj = auth
          return true
        }
      })
      return obj.name
    }, // getAuthStr
  },
  mounted () {
    if (!this.items) {
      this.search()
    }
  }
}
</script>

// react-front/src/component/manage/list/User-list.jsx
import React from 'react'
import { Table, Button, Input, Form } from 'antd'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class UserSearch extends React.Component {
  state = {
    vlsible: false,
  }

  componentDidMount() {
    this.props.search()
  }

  method = {
    clickSearch: e => {
      this.props.search(this.props.form.getFieldsValue())
    },

    clickAdd: e => {
      this.props.edit()

    },

    renderButton: (render) => {
      return !this.props.onlySearch && render
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form
    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.id']}>{getFieldDecorator("id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.name']} >{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
            <Form.Item label={locale['label.dept']}>{getFieldDecorator("dept")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item className="search-buttons row">
              <Button onClick={this.method.clickSearch} icon="search" title={locale['label.search']} />
              {this.method.renderButton(
                <div className="inline">
                  <Button onClick={this.method.clickAdd} icon="plus" title={locale['label.add']} />
                </div>
              )}
            </Form.Item>
          </div>
        </Form>
      </div>
    )
  }
}

class UserList extends React.Component {
  state = {
    items: [],
    onDbClick: undefined,
  }

  method = {
    getAuthStr: (key) => {
      let obj = {}
      let list = this.props.authList
      for (let i = 0; i < list.length; i++) {
        let it = list[i]
        if (it.id === key) {
          obj = it
          break
        }
      }
      return obj.name
    },

    clickEdit: (id) => {
      this.props.edit(id)
    },

    search: (param) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/' + this.props.path,
        data: param,
        success: function (list) {
          $this.setState({ items: list })
        },

      })
    },

    renderButton: (render) => {
      return !this.props.onlySearch && render
    },
  }

  onRow = (record, index) => {
    return {
      onDoubleClick: e => { if (this.props.onDbClick) this.props.onDbClick(record) }
     }
  }

  render() {
    return (

      <div className="urm-list">
        <WrappedUserSearch {...this.props} search={this.method.search} />
        <Table className="table-striped" dataSource={this.state.items} pagination={false}
            bordered size={"small"} scroll={{ x: 1200, y: 500 }} rowKey="id" onRow={this.onRow}>
          <Table.Column title={locale['label.id']} dataIndex="id" width="130px" />
          <Table.Column title={locale['label.name']} dataIndex="name" width="130px" />
          <Table.Column title={locale['label.dept']} dataIndex="dept" width="130px" />
          <Table.Column title={locale['label.position']} dataIndex="positionName" width="130px" />
          <Table.Column title={locale['label.grade']} dataIndex="gradeName" width="130px" />
          <Table.Column title={locale['label.generalTel']} dataIndex="generalTelNo" width="130px" />
          <Table.Column title={locale['label.officeTel']} dataIndex="officeTelNo" width="130px" />
          <Table.Column title={locale['label.mobile']} dataIndex="celNo" width="130px" />
          <Table.Column title={locale['label.auth']} dataIndex="authId" width="130px" render={(val) => (this.method.getAuthStr(val))} />
          {this.method.renderButton(
            <Table.Column title="Operations" className="operations" width="100px" render={(val) =>
              (<Button onClick={e => this.method.clickEdit(val.id)} icon="edit" />)} />
          )}
        </Table>
      </div>

    );
  }
}

const WrappedUserSearch = Form.create({ name: 'user_search' })(UserSearch)
export default UserList
