// vue-front/src/components/rule/list/request/RequestTransfer.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item label="담당자">
          <el-input v-model="manager" class="search-id" @click.native.prevent="showUserList('mng')" readonly/>
        </el-form-item>
        <el-form-item label="이관자">
          <el-input v-model="transferor" class="search-id" @click.native.prevent="showUserList('trans')" readonly/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="clickConfirm">이관</el-button>
      </div>
    </div>

    <el-table ref="reqList" :data="items" height="500" border class="table-striped">
      <el-table-column type="selection" width="40"/>
      <el-table-column :label="$t('label.requestId')" prop="id" width="145"/>
      <el-table-column :label="$t('label.requestName')" prop="name"/>
      <el-table-column :label="$t('label.interfaceType')" width="95" :formatter="getInfTypeStr"/>
      <el-table-column :label="$t('label.interfaceId')" prop="interfaceId" width="120"/>
      <el-table-column :label="$t('label.sourceSystem')" prop="sendSystem.name" width="110" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.targetSystem')" prop="rcvSystem.name" width="110" :show-overflow-tooltip="true"/>
      <el-table-column label="등록자" prop="regId" width="110"/>
      <el-table-column label="송신자" prop="sendAdminId" width="110"/>
      <el-table-column label="수신자" prop="rcvAdminId" width="110"/>
    </el-table>
  </div>
</template>
<script>
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  data () {
    return {
      tgtType: '',
      manager: '',
      transferor: '',
      items: [],
    }
  },
  methods: {
    getRequests (id) {
      const loading = this.$startLoading()
      this.$http.get('/api/request/list', {
        params: {loginUser: id},
      }).then(response => {
        this.items = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // getRequests

    clickConfirm () {
      if (!this.manager || this.manager.length === 0) {
        this.$message.warning('담당자가 선택되지 않았습니다.')
        return false
      }
      if (!this.transferor || this.transferor.length === 0) {
        this.$message.warning('이관자가 선택되지 않았습니다.')
        return false
      }

      let checkedList = this.$refs.reqList.selection
      if (checkedList.length <= 0) {
        this.$message.warning('선택된 요건이 없습니다.')
        return
      }
      let confirmProp = {
        confirmButtonText: 'YES',
        cancelButtonText: 'NO',
        closeOnClickModal: false,
        dangerouslyUseHTMLString: false,
        type: 'error',
      }
      this.$confirm(checkedList.length + ' 의 요건이 선택되었습니다. 이관하시겠습니까?', confirmProp).then(() => {
        checkedList.forEach((req) => {
          req.regId = this.transferor
          req.sendAdminId = this.transferor
          req.rcvAdminId = this.transferor
        })
        this.$emit('confirm', checkedList)
      }).catch(() => {
        this.$message.info('취소되었습니다.')
      })
    },

    showUserList (type) {
      this.tgtType = type
      this.$emit('show-usr-list', this.cbUserRowClick)
    }, // showUserList

    cbUserRowClick (row) {
      if (this.tgtType === 'mng') {
        this.manager = row.id
        this.getRequests(row.id)
      } else if (this.tgtType === 'trans') {
        this.transferor = row.id
      }
    }, // cbUserRowClick

    getInfTypeStr (row) {
      let kind = RuleUtil.CODEKEY.infType
      let codes = this.$store.state.codes
      let obj = {}
      codes.some((code) => {
        if (code.kind === kind && code.code === row.interfaceType) {
          obj = code
          return true
        }
      })
      return obj.name
    }, // getTypeStr
  },
}
</script>

// react-front/src/component/rule/list/sub/RequestTransfer.jsx
import React from 'react'
import { Table, Button, Modal, message } from 'antd'
import { Form, Input } from 'antd'

import SubModal from '@/component/SubModal'
import UserList from '@/component/manage/list/User-list'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class TransferForm extends React.Component {
  method = {
    confirm: e => {
      let userId = this.props.form.getFieldValue('userId')
      let trnUserId = this.props.form.getFieldValue('trnUserId')
      if (!userId || userId.trim().length === 0) {
        message.warning('담당자가 선택되지 않았습니다.')
        return false
      }
      if (!trnUserId || trnUserId.trim().length === 0) {
        message.warning('이관자가 선택되지 않았습니다.')
        return false
      }
      
      this.props.confirm(trnUserId)
    },

    setUser: (type) => {
      let ref = this.refs.usrList
      let form = this.props.form
      
      let callback = (user) => {
        if (type === 'now') {
          this.props.search({loginUser: user.id})
          form.setFieldsValue({userId: user.id})
        } else if (type === 'trn') {
          form.setFieldsValue({trnUserId: user.id})
        }
        ref.setState({visible: false})
      }

      let childState = {
        list: {onDbClick: callback}
      }
      ref.setState({visible: true, childState: childState})
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label="담당자">
              {getFieldDecorator("userId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setUser('now') }} />)}
            </Form.Item>
            <Form.Item label="이관자">
              {getFieldDecorator("trnUserId")(<Input size="small" readOnly allowClear className="search-id" onClick={e => { this.method.setUser('trn') }} />)}
            </Form.Item>
            <Form.Item className="search-buttons row">
              <Button icon="save" onClick={this.method.confirm} />
            </Form.Item>
          </div>
        </Form>

        <SubModal ref="usrList" width="1110px">
          <UserList key="list" path="user" authList={this.props.authList} onlySearch={true} />
        </SubModal>
      </div>
    );
  }
}

class RequestTransfer extends React.Component {
  state = {
    items: [],
    selectors: [],
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.items !== nextState.items) {
      return true
    }
    if (this.props.codeList && this.props.codeList.length !== nextProps.codeList.length) {
      return true
    }
    return false
  }

  method = {
    getTypeStr: (key, val) => {
      let kind = urmsc.CODEKEY[key]
      let list = this.props.codeList
      let obj = {}
      
      for(let i=0; i < list.length; i++) {
        let it = list[i]
        if (it.kind === kind && it.code === val) {
          obj = it
          break
        }
      }
      return obj.name
    },

    search: (param) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/request/list',
        data: param,
        success: function(res) {
          $this.setState({ items: res })
        },
      })
    },

    transfer: (trnUserId) => {
      let tmp = [...this.state.selectors]
      if (tmp.length === 0) {
        message.warning('선택된 요건이 없습니다.')
        return false
      }
      tmp.forEach((it) => {
        it.regId = trnUserId
        it.sendAdminId = trnUserId
        it.rcvAdminId = trnUserId
      })
      Modal.confirm({
        autoFocusButton: 'cancel',
        content: tmp.length + ' 의 요건이 선택되었습니다. 이관하시겠습니까?',
        cancelText: 'NO',
        okText: 'YES',
        onOk() {
          urmsc.ajax({
            type: 'POST',
            url: 'api/request/transfer',
            data: JSON.stringify(tmp),
            contentType: 'applicaion/json; charset=UTF-8',
            success: function(res) {
              message.success(res + " 의 요건이 성공적으로 이관되었습니다.")
            }
          })
        },
        onCancel() {
          message.info('취소되었습니다.')
        }
      })
    },
  }
  
  rowSelection = {
    columnWidth: 40,
    onSelect: (record, selected, selectedRows, nativeEvent) => {
      let tmp = []
      selectedRows.forEach((it) => {
        tmp.push(it)
      })
      this.setState({selectors: tmp})
    },
    onSelectAll: (selected, selectedRows, changeRows) => {
      let tmp = []
      selectedRows.forEach((it) => {
        tmp.push(it)
      })
      this.setState({selectors: tmp})
    },
  }

  render() {
    return (
      <div className="urm-list">
        <WrappedTransferForm {...this.props} search={this.method.search} confirm={this.method.transfer} />
        <Table className="table-striped"
          dataSource={this.state.items} pagination={false} bordered
          size="small" scroll={{ y: 500 }} rowKey="id"
          rowSelection={this.rowSelection}>
          <Table.Column title={locale['label.requestId']} dataIndex="id" width="145px" />
          <Table.Column title={locale['label.requestName']} dataIndex="name" width="180px" />
          <Table.Column title={locale['label.interfaceType']} dataIndex="interfaceType" render={(val) => ( this.method.getTypeStr('infType', val) )} />
          <Table.Column title={locale['label.interfaceId']} dataIndex="interfaceId" width="120px"/>
          <Table.Column title={locale['label.sourceSystem']} dataIndex="sendSystem.name" width="110px"/>
          <Table.Column title={locale['label.targetSystem']} dataIndex="rcvSystem.name" width="110px"/>
          <Table.Column title="등록자" dataIndex="regId" width="110px"/>
          <Table.Column title="송신자" dataIndex="sendAdminId" width="110px"/>
          <Table.Column title="수신자" dataIndex="rcvAdminId" width="110px"/>
        </Table>
      </div>
    );
  }
}

const WrappedTransferForm = Form.create({name:'transfer_form'})(TransferForm)
export default RequestTransfer
