// vue-front/src/components/statics/list/RequestChangeList.vue
<template>
  <div class="urm-list">
    <el-table ref="table" :height="listHeight" border class="table-striped">
      <el-table-column label="변경일자" prop="chgDate" width="150"/>
      <el-table-column label="변경요청">
        <el-table-column label="온라인" prop="stat1o" />
        <el-table-column label="배치" prop="stat1b" />
        <el-table-column label="디퍼드" prop="stat1d"/>
        <el-table-column label="TOTAL" prop="stat1" />
      </el-table-column>
      <el-table-column label="변경완료">
        <el-table-column label="온라인" prop="stat2o"/>
        <el-table-column label="배치" prop="stat2b"/>
        <el-table-column label="디퍼드" prop="stat2d"/>
        <el-table-column label="TOTAL" prop="stat2"/>
      </el-table-column>
      <el-table-column label="삭제요청">
        <el-table-column label="온라인" prop="stat3o"/>
        <el-table-column label="배치" prop="stat3b"/>
        <el-table-column label="디퍼드" prop="stat3d"/>
        <el-table-column label="TOTAL" prop="stat3"/>
      </el-table-column>
      <el-table-column label="삭제완료">
        <el-table-column label="온라인" prop="stat4o"/>
        <el-table-column label="배치" prop="stat4b"/>
        <el-table-column label="디퍼드" prop="stat4d"/>
        <el-table-column label="TOTAL" prop="stat4"/>
      </el-table-column>
    </el-table>
  </div>
</template>

// react-front/src/component/statics/list/RequestChange-list.jsx
import React from 'react'
import { Table } from 'antd'

export default class ChangeList extends React.Component {
  state = {
    items: [],
  }

  render() {
    return (
      <div className="urm-list">
        <Table className="table-striped"
            dataSource={this.state.items} pagination={false} bordered
            size="small" rowKey="chgDate">
          <Table.Column title="변경일자" dataIndex="chgDate" width="130px"/>
          <Table.ColumnGroup title="변경요청">
            <Table.Column title="온라인" dataIndex="stat1o" />
            <Table.Column title="배치" dataIndex="stat1b" />
            <Table.Column title="디퍼드" dataIndex="stat1d" />
            <Table.Column title="TOTAL" dataIndex="stat1" />
          </Table.ColumnGroup>
          <Table.ColumnGroup title="변경완료">
            <Table.Column title="온라인" dataIndex="stat2o" />
            <Table.Column title="배치" dataIndex="stat2b" />
            <Table.Column title="디퍼드" dataIndex="stat2d" />
            <Table.Column title="TOTAL" dataIndex="stat2" />
          </Table.ColumnGroup>
          <Table.ColumnGroup title="삭제요청">
            <Table.Column title="온라인" dataIndex="stat3o" />
            <Table.Column title="배치" dataIndex="stat3b" />
            <Table.Column title="디퍼드" dataIndex="stat3d" />
            <Table.Column title="TOTAL" dataIndex="stat3" />
          </Table.ColumnGroup>
          <Table.ColumnGroup title="삭제완료">
            <Table.Column title="온라인" dataIndex="stat4o" />
            <Table.Column title="배치" dataIndex="stat4b" />
            <Table.Column title="디퍼드" dataIndex="stat4d" />
            <Table.Column title="TOTAL" dataIndex="stat4" />
          </Table.ColumnGroup>
        </Table>
      </div>
    );
  }
}
