// vue-front/src/components/rule/Request.vue
<template>
  <div class="urm-panel">
    <RequestList ref="list" @edit="handleEdit"/>

    <el-dialog title="Editor" :visible.sync="editorShow" width="1080px">
      <RequestEditor ref="editor" :item="editorItem" @save="handleSave"/>
    </el-dialog>
  </div>
</template> 

<script>
import RuleMain from './RuleMain'

export default {
  mixins: [RuleMain],
  data () {
    return {
      path: 'request',
    }
  },
  methods: {
    getNewItem () {
      return {
        id: '',
        name: '',
        fields: [],
      }
    }, // getNewItem
    initData (item) {
      let newItem = this.getNewItem()
      if (!item.fields) {
        item.fields = newItem.fields
      }
    }
  },
}
</script>

// react-front/src/component/rule/Request.jsx
import React from 'react'

import RuleMain from './RuleMain'
import RequestList from './list/Request-list'
import RequestEditor from './editor/Request-editor'

export default class Request extends RuleMain {
  constructor (props) {
    super(props)
    this.state = {
      path: 'request'
    }
  }
  
  authList = () => {
    let authList = this.props.authCode
    return authList ? authList : []
  }
  
  render() {
    return (
      <div className="urm-panel" style={{minWidth: 1315}}>
        <RequestList ref="list" path={this.state.path} userInfo={this.props.userInfo}
          codeList={this.codeList()} authList={this.authList()} edit={this.method.handleEdit} />
        <RequestEditor ref="editor" path={this.state.path} userInfo={this.props.userInfo}
          codeList={this.codeList()} authList={this.authList()} save={this.method.handleSave} />
      </div>
    );
  }
}
