// vue-front/src/components/rule/RuleMain.vue
<script>
import Vue from 'vue'

import DataList from './list/DataList'
import SystemList from './list/SystemList'
import RequestList from './list/RequestList'

import DataEditor from './editor/DataEditor'
import SystemEditor from './editor/SystemEditor'
import RequestEditor from './editor/RequestEditor'

Vue.component('DataList', DataList)
Vue.component('SystemList', SystemList)
Vue.component('RequestList', RequestList)

Vue.component('DataEditor', DataEditor)
Vue.component('SystemEditor', SystemEditor)
Vue.component('RequestEditor', RequestEditor)

export default {
  data () {
    return {
      listItem: null,
      editorShow: false,
      editorItem: null,
    }
  },
  methods: {
    handleSearch (sparam) {
      const loading = this.$startLoading()
      console.log('search : ' + this.path, sparam)
      this.$http.get('/api/' + this.path, {
        params: sparam,
      }).then(response => {
        this.listItem = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // search

    handleEdit (id) {
      if (id) {
        console.log('edit : ' + id)
        this.$http.get('/api/' + this.path + '/' + id, {
        }).then(response => {
          this.editorItem = response.data
          this.initData(this.editorItem)
          this.editorShow = true
        })
      } else {
        this.editorItem = this.getNewItem()
        this.editorShow = true
      }
    }, // handleEdit

    handleSave (item) {
      console.log('save', item)
      this.$http({
        method : 'POST',
        url: '/api/' + this.path,
        data: item,
      }).then(response => {
        this.$message({message: this.$t('message.0001'), type: 'success'})
        item.id = response.data.id
        this.handleSearch(this.$refs.list.sparam)
      }).catch(error => {
        this.$handleHttpError(error)
      })
    }, // handleSave
  }
}
</script>

// react-front/src/component/rule/RuleMain.jsx
import React from 'react'
import * as urmsc from '../../urm-utils'

import RequestList from './list/Request-list'
import RequestEditor from './editor/Request-editor'
import DataList from './list/Data-list'
import DataEditor from './editor/Data-editor'
import SystemList from './list/System-list'
import SystemEditor from './editor/System-editor'


const LIST_STATE = urmsc.LIST_STATE

export default class RuleMain extends React.Component {
  componentDidMount() {
    console.log('mounted')
  }

  method = {
    handleEdit: (id) => {
      if (id) {
        let $this = this
        urmsc.ajax({
          type: 'GET',
          url: '/URM/' + this.state.path + '/' + id,
          success: function(res) {
            let $editor = $this.refs.editor
            console.log(res)
            $editor.setState({visible: true, item: res})
          }
        })
      } else {
        this.refs.editor.setState({visible: true, item: {}})
      }
    },
    
    handleSave: (data, comp) => {
      let $this = this
      urmsc.ajax({
        type: 'POST',
        url: '/URM/' + this.state.path,
        data: JSON.stringify(data),
        contentType: 'application/json; charset=UTF-8',
        success: function(res) {
          let $editor = $this.refs.editor
          console.log(res)
          $editor.setState({item: res})
          
          let $list = $this.refs.list
          $list.method._updateItems(LIST_STATE.UPDATE, res)
        }
      })
    }
  }
  
  getCode = () => {
    let codeList = this.props.commonCode
    return codeList ? codeList : []
  }
  
  components = {
    RequestList: RequestList,
    RequestEditor: RequestEditor,
    DataList: DataList,
    DataEditor: DataEditor,
    SystemList: SystemList,
    SystemEditor: SystemEditor,
  }
}
