// vue-front/src/components/rule/System.vue
<template>
  <div class="urm-panel">
    <SystemList ref="list" @edit="handleEdit"/>
   
    <el-dialog title="Editor" :visible.sync="editorShow" width="1080px">
      <SystemEditor ref="editor" :item="editorItem" @save="handleSave"/>
    </el-dialog>
  </div>
</template> 

<script>
import RuleMain from './RuleMain'

export default {
  mixins: [RuleMain],
  data () {
    return {
      path: 'system',
    }
  },
  methods: {
    getNewItem () {
      return {
        id: '',
        name: '',
        fields: [],
      }
    }, // getNewItem
    initData (item) {
      let newItem = this.getNewItem()
      if (!item.fields) {
        item.fields = newItem.fields
      }
    }
  },
}
</script>

// react-front/src/component/rule/System.jsx
import React from 'react'

import RuleMain from './RuleMain'
import SystemList from './list/System-list'
import SystemEditor from './editor/System-editor'

class System extends RuleMain {
  constructor (props) {
    super(props)
    this.state = {
      path: 'system',
    }
  }

  render() {
    return (
      <div className="urm-panel">
        <SystemList ref="list" path={this.state.path} userInfo={this.props.userInfo}
          codeList={this.codeList()} edit={this.method.handleEdit} />
        <SystemEditor ref="editor" path={this.state.path} userInfo={this.props.userInfo}
          codeList={this.codeList()} save={this.method.handleSave} />
      </div>
    );
  }
}

export default System
