// vue-front/src/components/rule/list/DataList.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.dataId')">
          <el-input v-model="sparam.id" class="search-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.dataName')">
          <el-input v-model="sparam.name" class="search-name"/>
        </el-form-item>
        <el-form-item :label="$t('label.dataType')">
          <el-select v-model="sparam.type" class="search-id">
            <el-option value="" label="ALL"/>
            <el-option v-for="type in dataTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
        <el-button @click="clickEdit()" v-if="!onlySearch">{{$t('label.add')}}</el-button>
        <el-button @click="clickDelete('selected')" v-if="!onlySearch">{{$t('label.delete')}}</el-button>
      </div>
    </div>

    <el-table ref="table" :data="items" :height="listHeight" border class="table-striped">
      <el-table-column type="selection" width="40"/>
      <el-table-column :label="$t('label.id')" prop="id" width="150"/>
      <el-table-column :label="$t('label.name')" prop="name"/>
      <el-table-column :label="$t('label.dataType')" width="100">
        <template slot-scope="scope">
          <span>{{getTypeStr('dataType', scope.row.type)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.registId')" prop="regId" width="200"/>
      <el-table-column :label="$t('label.registDate')" width="200">
        <template slot-scope="scope">
          <span>{{scope.row.regDate}}</span>
        </template>
      </el-table-column>
      <el-table-column width="150" class-name="edit-cell operations">
        <template slot-scope="scope">
          <div>
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row.id)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row.id)" plain/>
            <el-button icon="el-icon-connection" @click.stop="clickUsed(scope.row.id)"/>
          </div>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>
<script>
import RuleList from './RuleList'
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  mixins: [RuleList],
  data () {
    return {
      path: 'data',
      listHeight: 'calc(100vh - 165px)',
      sparam: {
        ...this.sparam,
        type: '',
      },
    }
  },
  methods: {
    clickUsed (id) {
      console.log('used', id)
    }, // clickUsed
  },
  computed: {
    dataTypes: function () {
      let kind = RuleUtil.CODEKEY.dataType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
  },
}
</script>

// react-front/src/components/rule/list/Data-list.jsx
import React from 'react'
import { Table, Button } from 'antd'
import { Form, Input, Select } from 'antd'
import moment from 'moment'

import RuleList, { RuleSearch } from './RuleList'
import SubModal from '@/components/SubModal'
import UsedData from './sub/UsedData'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class DataSearch extends RuleSearch {
  method = {
    ...this.method,

    renderOpts: (key) => {
      return urmsc.getSubListByKey(this.props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form

    return (
      <div className={'search-bar ' + this.props.path}>
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.dataId']}>{getFieldDecorator("id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.dataName']}>{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
            <Form.Item label={locale['label.dataType']}>
              {getFieldDecorator("type", {initialValue: ""})(<Select size="small" className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("dataType")}
              </Select>)}
            </Form.Item>
            <Form.Item className="search-buttons">
              <Button size="small" onClick={this.method.clickSearch}>{locale['label.search']}</Button>
              {this.method.renderButton(
                <div className="inline">
                  <Button size="small" onClick={this.method.clickAdd}>{locale['label.add']}</Button>
                  <Button size="small" type="danger" onClick={this.method.clickDelete} disabled={!this.props.canDelete()}>{locale['label.delete']}</Button>
                </div>
              )}
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

class DataList extends RuleList {
  method = {
    ...this.method,

    clickUsed: (id) => {
      let ref = this.refs.usedList
      let childState = {
        list: {dataId: {id: id}}
      }
      ref.setState({visible: true, childState: childState})
    }
  }

  render() {
    return (
      <div className="urm-list">
        <WrappedDataSearch  {...this.props} search={this.method.search} delete={this.method.clickDelete} canDelete={this.method.isPageDelete} />
        <Table className="table-striped"
            dataSource={this.state.items} pagination={false} bordered
            size="small" /*scroll={{ y: 500 }}*/ rowKey="id"
            rowSelection={this.rowSelection} onRow={this.onRow}>
          <Table.Column title={locale['label.id']} dataIndex="id" width="150px"/>
          <Table.Column title={locale['label.name']} dataIndex="name" ellipsis />
          <Table.Column title={locale['label.dataType']} dataIndex="type" width="100px" render={(val) => ( this.method.getTypeStr('dataType', val) )} />
          <Table.Column title={locale['label.registId']} dataIndex="regId" width="200px" ellipsis />
          <Table.Column title={locale['label.registDate']} dataIndex="regDate" width="200px" render={(val) => ( moment(val).format('YYYY-MM-DD HH:mm:ss') )} />
          {this.method.renderButton(
            <Table.Column className="operations" width="115px" render={(val) =>
              (<div>
                <Button icon="edit" onClick={e => { this.method.clickEdit(val.id) }} title={locale['label.modify']} />
                <Button icon="delete" type="danger" onClick={e => { this.method.clickDelete([val.id]) }} title={locale['label.delete']} disabled={!this.method.isPageDelete()} />
                <Button icon="interaction" onClick={e => { this.method.clickUsed(val.id) }} title="영향도" />
              </div>)}
            />
          )}
        </Table>
        
        <SubModal ref="usedList" width="900px" destroyOnClose>
          <UsedData key="list" isEditor={false} />
        </SubModal>
      </div>
    );
  }
}

const WrappedDataSearch = Form.create({name:'data_search'})(DataSearch)
export default DataList
