// react-front/src/component/rule/Data.jsx
import React from 'react'
import RuleMain from './RuleMain'

export default class Data extends RuleMain {
  constructor (props) {
    super(props)
    this.state = {
      path: 'data',
    }
  }

  render() {
    const { DataList, DataEditor} = this.components
    
    return (
      <div className="urm-panel">
        <DataList ref="list" path={this.state.path} codeList={this.getCode()} edit={this.method.handleEdit} />
        <DataEditor ref="editor" path={this.state.path} codeList={this.getCode()} save={this.method.handleSave} />
      </div>
    );
  }
}

// vue-front/src/components/rule/Data.vue
<template>
  <div class="urm-panel">
    <DataList ref="list" @edit="handleEdit"/>

    <el-dialog :visible.sync="editorShow" width="1080px">
      <DataEditor ref="editor" :item="editorItem" @save="handleSave"/>
    </el-dialog>
  </div>
</template>

<script>
import RuleMain from './RuleMain'

export default {
  mixins: [RuleMain],
  data () {
    return {
      path: 'data',
    }
  },
  methods: {
    getNewItem () {
      return {
        id: '',
        fields: [],
      }
    }, // getNewItem
    initData (item) {
      let newItem = this.getNewItem()
      if (!item.fields) {
        item.fields = newItem.fields
      }
    }, // initData
  },
}
</script>
