// react-front/src/components/process/stat/list/StaticsDay-list.jsx
import React from 'react'
import { Table } from 'antd'

export default class StaticsDayList extends React.Component {
  state = {
    items: [],
  }
  
  renderSim = () => {
    let type = this.props.match.params.path.charAt(0)
    let infType = this.props.match.params.path.charAt(5)
    if (type === 'd' && infType === '4') {
      return <Table.Column title="시뮬레이션건수" dataIndex="simCount" />
    }
    return undefined
  }
  
  getRowKey = (record) => {
    return this.state.items.indexOf(record)
  }

  render() {
    return (
      <div className="urm-list">
        <Table className="table-striped"
            dataSource={this.state.items} pagination={false} bordered
            size="small" rowKey={this.getRowKey}>
          <Table.Column title="처리날짜" dataIndex="processDate" />
          <Table.Column title="인터페이스ID" dataIndex="interfaceId" width="200px" />
          <Table.Column title="총건수" dataIndex="totalCount" />
          {this.renderSim()}
          <Table.Column title="성공건수" dataIndex="successCount" />
          <Table.Column title="실패건수" dataIndex="failCount" />
          <Table.Column title="평균처리시간" dataIndex="processTime" />
        </Table>
      </div>
    );
  }
}

// vue-front/src/components/process/statics/list/StaticsDayList.vue
<template>
  <div class="urm-list">
    <el-table :data="items" :height="listHeight" border stripe>
      <el-table-column label="처리날짜" prop="processDate"/>
      <el-table-column label="인터페이스ID" prop="interfaceId" width="200"/>
      <el-table-column label="총건수" prop="totalCount"/>
      <el-table-column label="성공건수" prop="successCount"/>
      <el-table-column label="실패건수" prop="failCount"/>
      <el-table-column label="평균처리시간" prop="processTime"/>
    </el-table>
  </div>
</template>

<script>
export default {
  data () {
    return {
      listHeight: 'calc(100vh - 195px)',
      items: [],
    }
  },
}
</script>
