// react-front/src/component/statics/list/RequestProcess-list.jsx
import React from 'react'
import { Table } from 'antd'

export default class ProcessList extends React.Component {
  state = {
    items: [],
  }

  render() {
    return (
      <div className="urm-list">
        <Table className="table-striped"
            dataSource={this.state.items} pagination={false} bordered
            size="small" rowKey="chgDate">
          <Table.Column title="변경일자" dataIndex="chgDate" width="130px"/>
          <Table.Column title="요건신청" dataIndex="stat1" />
          <Table.Column title="재작성요청" dataIndex="stat2" />
          <Table.Column title="접수완료" dataIndex="stat3" />
          <Table.Column title="반려" dataIndex="stat4" />
          <Table.Column title="요건등록완료" dataIndex="stat5" />
          <Table.Column title="대표거래테스트" dataIndex="stat6" />
          <Table.Column title="테스트중" dataIndex="stat7" />
          <Table.Column title="테스트완료" dataIndex="stat8" />
          <Table.Column title="테스트이관요청" dataIndex="stat9" />
          <Table.Column title="테스트이관" dataIndex="stat10" />
          <Table.Column title="운영이관요청" dataIndex="stat11" />
          <Table.Column title="운영이관" dataIndex="stat12" />
          <Table.Column title="TOTAL" dataIndex="count" />
        </Table>
      </div>
    );
  }
}

// vue-front/src/components/statics/list/RequestProcessList.vue
<template>
  <div class="urm-list">
    <el-table ref="table" :data="items" :height="listHeight" border class="table-striped">
      <el-table-column label="변경일자" prop="chgDate" width="130"/>
      <el-table-column label="요건신청" prop="stat1"/>
      <el-table-column label="재작성요청" prop="stat2"/>
      <el-table-column label="접수완료" prop="stat3"/>
      <el-table-column label="반려" prop="stat4"/>
      <el-table-column label="요건등록완료" prop="stat5" width="130"/>
      <el-table-column label="대표거래테스트" prop="stat6" width="130"/>
      <el-table-column label="테스트중" prop="stat7"/>
      <el-table-column label="테스트완료" prop="stat8"/>
      <el-table-column label="테스트이관요청" prop="stat9" width="130"/>
      <el-table-column label="테스트이관" prop="stat10"/>
      <el-table-column label="운영이관요청" prop="stat11" width="130"/>
      <el-table-column label="운영이관" prop="stat12"/>
      <el-table-column label="TOTAL" prop="count"/>
    </el-table>
  </div>
</template>

<script>
export default {
  data () {
    return {
      listHeight: 'calc(100vh - 600px)',
    }
  },
  props: ['items']
}
</script>
