// vue-front/src/components/rule/editor/SystemEditor.vue
<template>
  <div class="urm-editor">
    <div class="editor-buttons">
      <el-button @click="clickSave" plain>{{$t('label.save')}}</el-button>
    </div>
    <el-form label-width="140px" style="margin-top: 15px;">
      <div class="row">
        <el-form-item :label="$t('label.systemId')">
          <el-input v-model="item.id" class="size-id" disabled/>
        </el-form-item>
        <el-form-item :label="$t('label.systemCd')">
          <el-input v-model="item.code" class="size-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.systemName')">
          <el-input v-model="item.name" class="size-name"/>
        </el-form-item>
      </div>
      <div class="row">
        <el-form-item :label="$t('label.systemType')">
          <el-select v-model="item.type" class="size-id">
            <el-option v-for="type in sysTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('label.devType')">
          <el-select v-model="item.devType" class="size-id">
            <el-option v-for="type in devTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
      </div>
      <div class="row">
        <el-form-item :label="$t('label.host')">
          <el-input v-model="item.hostId" class="size-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.ip')">
          <el-input v-model="item.ip" class="size-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.port')">
          <el-input v-model="item.port" class="size-name"/>
        </el-form-item>
      </div>
      <div class="row">
        <el-form-item :label="$t('label.id')">
          <el-input v-model="item.userId" class="size-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.pass')">
          <el-input v-model="item.userPasswd" class="size-id"/>
        </el-form-item>
      </div>
      <div v-show="item.type === '2'">
        <div class="row">
          <el-form-item :label="$t('label.dbType')">
            <el-select v-model="item.dbType" class="size-id">
              <el-option v-for="type in dbTypes" :value="type.code" :label="type.name" :key="type.code"/>
            </el-select>
          </el-form-item>
          <el-form-item :label="$t('label.jdbcType')">
            <el-select v-model="item.jdbcType" class="size-id">
              <el-option value="1" label="1"/>
              <el-option value="2" label="2"/>
              <el-option value="3" label="3"/>
              <el-option value="4" label="4"/>
            </el-select>
          </el-form-item>
          <el-form-item :label="$t('label.dbName')">
            <el-input v-model="item.dbName" class="size-name"/>
          </el-form-item>
        </div>
        <div class="row">
          <el-form-item :label="$t('label.connectParam')">
            <el-input type="textarea" v-model="item.dbParams" class="size-default"/>
          </el-form-item>
        </div>
      </div>
      <div class="row">
        <el-form-item :label="$t('label.etcRemark')">
          <el-input type="textarea" v-model="item.remark" class="size-default"/>
        </el-form-item>
      </div>
    </el-form>
  </div>
</template>

<script>
import RuleEditor from './RuleEditor'
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  mixins: [RuleEditor],
  props: {
    sysTypes: {
      type: Array,
      default: () => [],
    },
    devTypes: {
      type: Array,
      default: () => [],
    },
  },
  methods: {
    customValidator () {
      if (this.item.type !== '2') {
        this.item.dbType = null
        this.item.jdbcType = null
        this.item.dbName = null
        this.item.dbParams = null
      }
    },
  },
  computed: {
    dbTypes: function () {
      let kind = RuleUtil.CODEKEY.dbType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
  },
}
</script>

<style scoped>
.size-default {
  width: 490px;
}
</style>

// react-front/src/components/rule/editor/System-editor.jsx
import React, { useEffect } from 'react'
import { Button, Modal } from 'antd'
import { Form, Input, Select } from 'antd'

import RuleEditor from './RuleEditor'
import * as urmsc from '../../../urm-utils'

const locale = urmsc.locale

const KINDS = urmsc.CODEKEY

class SystemEditor extends RuleEditor {
  render() {
    return (
      <Modal visible={this.state.visible} width="1068px"
          footer={null} onCancel={this.method.handleCancel} className="urm-modal">
        <WrappedSystemEditor codeList={this.props.codeList} item={this.state.item} {...this.childMethod} />
      </Modal>
    );
  }
}

const SystemEditorForm = (props) => {
  const { form, item } = props
  const { getFieldDecorator } = form

  useEffect(() => {
    props.setItem(form, item, method.initialSetter)
    item.subRule = {
      dbType: item.dbType,
      jdbcType: item.jdbcType,
      dbName: item.dbName,
      dbParams: item.dbParams
    }
    // eslint-disable-next-line
  }, [item]); // Only re-run the effect if props.item changes

  let method = {
    renderOpts: (key) => {
      return urmsc.getSubListByKey(props.codeList, 'kind', KINDS[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
    
    clickSave: e => {
      let saveItem = method.makeSystemObj()
      props.save(saveItem)
    },
    
    initialSetter: (formItem, propsItem) => {
      formItem.userPasswd = ''
    },
    
    makeSystemObj: () => {
      let saveItem = props.makeRuleObj(form, item)
      
      saveItem.dbType = undefined
      saveItem.jdbcType = undefined
      saveItem.dbName = undefined
      saveItem.dbParams = undefined
      if (saveItem.type === '2') {
        let children = item.subRule
        saveItem.dbType = children.dbType
        saveItem.jdbcType = children.jdbcType
        saveItem.dbName = children.dbName
        saveItem.dbParams = children.dbParams
      }
      
      return saveItem
    },
    
    renderDBSystem: () => {
      let type = form.getFieldValue('type')
      let children = item.subRule
      if (children && type === '2') {
        let dbTypeProps = {initialValue: !children.dbType ? '1' : children.dbType}
        let jdbcTypeProps = {initialValue: !children.jdbcType ? '1' : children.jdbcType}
        let dbNameProps = {initialValue: !children.dbName ? '' : children.dbName}
        let dbParamsProps = {initialValue: !children.dbParams ? '' : children.dbParams}
        
        if (item.type !== '2') {
          let fields = form.getFieldsValue()
          if (fields.dbType) {
            children.dbType = fields.dbType
            children.jdbcType = fields.jdbcType
            children.dbName = fields.dbName
            children.dbParams = fields.dbParams
          }
        }
        
        return (
          <div>
            <div className="row">
              <Form.Item label={locale['label.dbType']}>
                {getFieldDecorator("dbType", dbTypeProps)(<Select size="small" className="size-id">
                  {method.renderOpts("dbType")}
                </Select>)}
              </Form.Item>
              <Form.Item label={locale['label.jdbcType']}>
                {getFieldDecorator("jdbcType", jdbcTypeProps)(<Select size="small" className="size-id">
                  <Select.Option value="1">1</Select.Option>
                  <Select.Option value="2">2</Select.Option>
                  <Select.Option value="3">3</Select.Option>
                  <Select.Option value="4">4</Select.Option>
                </Select>)}
              </Form.Item>
              <Form.Item label={locale['label.dbName']}>{getFieldDecorator("dbName", dbNameProps)(<Input size="small" className="size-name" />)}</Form.Item>
            </div>
            <div className="row">
              <Form.Item label={locale['label.connectParam']}>{getFieldDecorator("dbParams", dbParamsProps)(<Input.TextArea className="urm-remark" />)}</Form.Item>
            </div>
          </div>
        );
      }
      return undefined
    },

  }

  return (
    <div className="urm-editor">
      <div className="editor-buttons">
        <Button onClick={method.clickSave} disabled={!props.isPageSave()}>{locale['label.save']}</Button>
      </div>
      <Form colon={false}>
        <div className="row">
          <Form.Item label={locale['label.systemId']}>{getFieldDecorator("id")(<Input size="small" className="size-id" readOnly />)}</Form.Item>
          <Form.Item label={locale['label.systemCd']}>{getFieldDecorator("code")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.systemName']}>{getFieldDecorator("name")(<Input size="small" className="size-name" />)}</Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.systemType']}>
            {getFieldDecorator("type", {initialValue: "1"})(<Select size="small" className="size-id">
              {method.renderOpts("sysType")}
            </Select>)}
          </Form.Item>
          <Form.Item label={locale['label.devType']}>
            {getFieldDecorator("devType", {initialValue: "1"})(<Select size="small" className="size-id">
              {method.renderOpts("devType")}
            </Select>)}
          </Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.host']}>{getFieldDecorator("hostId")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.ip']}>{getFieldDecorator("ip")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.port']}>{getFieldDecorator("port")(<Input size="small" className="size-name" />)}</Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.id']}>{getFieldDecorator("userId")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.pass']}>{getFieldDecorator("userPasswd")(<Input.Password size="small" className="size-id" visibilityToggle={false} />)}</Form.Item>
        </div>
        {method.renderDBSystem()}
        <div className="row">
          <Form.Item label={locale['label.etcRemark']}>{getFieldDecorator("remark")(<Input.TextArea className="urm-remark" />)}</Form.Item>
        </div>
      </Form>
    </div>
  );
}

const WrappedSystemEditor = Form.create({name:'system_editor'})(SystemEditorForm)
export default SystemEditor
