// react-front/src/component/rule/editor/Request-editor.jsx
import React, { useEffect } from 'react'
import { Button, Modal, Popover, DatePicker, message } from 'antd'
import { Form, Input, Select, Radio, Switch, Checkbox, Upload } from 'antd'
import moment from 'moment'

import RuleEditor from './RuleEditor'
import SubModal from '@/component/SubModal'

import DataMapEditor from './DataMap-editor'
import DataMapList from '@/component/rule/list//DataMap-list'
import SystemList from '@/component/rule/list/System-list'
import BizList from '@/component/manage/list/BizCode-list'
import UserList from '@/component/manage/list/User-list'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class RequestEditor extends RuleEditor {
  customMethod = {
    validator: (data) => {
      if (!data.sendSystemId || data.sendSystemId.trim().length === 0) {
        message.warning(locale['message.1008'])
        return false
      }
      if (!data.rcvSystemId || data.rcvSystemId.trim().length === 0) {
        message.warning(locale['message.1009'])
        return false
      }
      if (!data.sendJobCodeId || data.sendJobCodeId.trim().length === 0) {
        message.warning(locale['message.1019'])
        return false
      }
      if (!data.rcvJobCodeId || data.rcvJobCodeId.trim().length === 0) {
        message.warning(locale['message.1019'])
        return false
      }
      if (!data.sendAdminId || data.sendAdminId.trim().length === 0) {
        data.sendAdminId = this.props.userInfo.id
      }
      if (!data.rcvAdminId  || data.rcvAdminId.trim().length === 0) {
        data.rcvAdminId = this.props.userInfo.id
      }
      
      if( !urmsc.isSelectAuth('prcStat', data.processStat, this.props.userInfo.auth) ) {
        message.warning(locale['message.1010']);
        return false
      }
      if( !urmsc.isSelectAuth('chgStat', data.chgStat, this.props.userInfo.auth) ) {
        message.warning('\'변경 신청\' 으로 수정합니다.');
        this.setState({ item: {...this.state.item, chgStat: 0} })
        return false
      }
      return true
    }
  }

  render() {
    return (
      <Modal visible={this.state.visible} width="1080px"
          footer={null} onCancel={this.method.handleCancel} className="urm-modal">
        <WrappedRequestEditor codeList={this.props.codeList} authList={this.props.authList}
          item={this.state.item} {...this.childMethod} />
      </Modal>
    );
  }
}

const RequestEditorForm = (props) => {
  const { form, item } = props
  const { getFieldDecorator } = form
  const { RangePicker } = DatePicker

  // Only re-run the effect if props.item changes
  useEffect(() => {
    props.setItem(form, item, method.initialSetter)
    item.children = {}
    // TODO subscribe...
    // eslint-disable-next-line
  }, [item]);

  let sysList = null;
  let bizList = null;
  let usrList = null;
  let mapList = null;
  let dataMap = null;

  let method = {
    clickSave: e => {
      let saveItem = method.makeRequestObj()
      props.save(saveItem)
    },

    initialSetter: (formItem, propsItem) => {
      formItem.testDate = [moment(propsItem.testStartYMD), moment(propsItem.testEndYMD)]
      formItem.sendSystemName = propsItem.sendSystem.name
      formItem.rcvSystemName = propsItem.rcvSystem.name
      formItem.sendJobCodeName = propsItem.sendJobCode.part2Name + '(' + propsItem.sendJobCode.part2Id + ')'
      formItem.rcvJobCodeName = propsItem.rcvJobCode.part2Name + '(' + propsItem.rcvJobCode.part2Id + ')'
      formItem.sendAdminName = propsItem.sendAdmin.name + '(' + propsItem.sendAdmin.positionName + ')'
      formItem.rcvAdminName = propsItem.rcvAdmin.name + '(' + propsItem.rcvAdmin.positionName + ')'
    },

    makeRequestObj: () => {
      let saveItem = props.makeRuleObj(form, item)
      
      let testDate = form.getFieldValue('testDate')
      saveItem.testStartYMD = testDate[0].format('YYYYMMDD')
      saveItem.testEndYMD = testDate[1].format('YYYYMMDD')
      
      let children = item.children
      if (children.sendSystem) saveItem.sendSystemId = children.sendSystem.id
      if (children.rcvSystem) saveItem.rcvSystemId = children.rcvSystem.id
      if (children.sendJobCode) saveItem.sendJobCodeId = children.sendJobCode.id
      if (children.rcvJobCode) saveItem.rcvJobCodeId = children.rcvJobCode.id
      if (children.sendAdmin) saveItem.sendAdminId = children.sendAdmin.id
      if (children.rcvAdmin) saveItem.rcvAdminId = children.rcvAdmin.id
      
      saveItem.sql = saveItem.sqlPlain
      
      return saveItem
    },

    getDataMapList: (type) => {
      let ref = mapList
      // TODO reuse mapping??
      
      ref.setState({visible: true})
    },

    editDataMap: (type, e) => {
      let ref = dataMap
      let id = e.target.value
      let callback = (id) => {
        if (type === 'req') {
          form.setFieldsValue({reqDataMappingId: id})
        } else if (type === 'res') {
          form.setFieldsValue({resDataMappingId: id})
        }
      }
      if (id && id.trim().length) {
        urmsc.ajax({
          type: 'GET',
          url: 'api/datamap/' + id,
          success: function(res) {
            ref.setState({visible: true, item: res, confirm: callback})
          }
        })
      } else {
        ref.setState({visible: true, item: {}, confirm: callback})
      }
    },

    setSystem: (type) => {
      let ref = sysList
      let children = item.children
      let callback = (system) => {
        if (type === 'rcv') {
          children.rcvSystem = system
          form.setFieldsValue({rcvSystemName: system.name})
        } else if (type === 'send') {
          children.sendSystem = system
          form.setFieldsValue({sendSystemName: system.name})
        }
        ref.setState({visible: false})
      }
      
      let sysType = '3'
      if (type === 'rcv') {
        sysType = form.getFieldValue('rcvSystemType')
      } else if (type === 'send') {
        sysType = form.getFieldValue('sendSystemType')
      }
      
      let childState = {
        list: { onDbClick: callback, scparam: {type: sysType} }
      }
      ref.setState({visible: true, childState: childState})
    },

    setBizCode: (type) => {
      let ref = bizList
      let children = item.children
      let callback = (biz) => {
        let name = biz.part2Name + '(' + biz.part2Id + ')'
        if (type === 'rcv') {
          children.rcvJobCode = biz
          form.setFieldsValue({rcvJobCodeName: name})
        } else if (type === 'send') {
          children.sendJobCode = biz
          form.setFieldsValue({sendJobCodeName: name})
        }
        ref.setState({visible: false})
      }
      
      let childState = {
        list: { onDbClick: callback }
      }
      ref.setState({visible: true, childState: childState})
    },

    setUser: (type) => {
      let ref = usrList
      let children = item.children
      let callback = (user) => {
        let name = user.name + '(' + user.positionName + ')'
        if (type === 'rcv') {
          children.rcvAdmin = user
          form.setFieldsValue({rcvAdminName: name})
        } else if (type === 'send') {
          children.sendAdmin = user
          form.setFieldsValue({sendAdminName: name})
        }
        ref.setState({visible: false})
      }
      
      let childState = {
        list: { onDbClick: callback }
      }
      ref.setState({visible: true, childState: childState})
    },

    setQuery: visible => {
      if (!visible) {
        form.setFieldsValue({sqlPlain: form.getFieldValue('sql')})
      } else {
        form.setFieldsValue({sql: item.sqlPlain})
      }
    },

    preventAction: (file) => {
      let formData = new FormData();
      formData.append('file', file, file.name)
      
      urmsc.ajax({
        type: 'POST',
        url: 'api/request/upload',
        data: formData,
        dataType: 'text',
        contentType: false,
        success: function(res) {
          message.success(locale['message.0007'] + ' - ' + res)
        }
      })
      return false
    },
    
    uploadFile: e => {
      return e && e.file
    },
    
    renderOpts: (key) => {
      return urmsc.getSubListByKey(props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },

    renderSendSystem: () => {
      let type = form.getFieldValue('sendSystemType')
      if (type === '2') {
        let sqlProps = {initialValue: item.sqlPlain}
        if (item.type !== '2') {
          let query = form.getFieldValue('sqlPlain')
          item.sqlPlain = (query && query.length > 0) ? query : item.sqlPlain
        }
        
        let textarea = <Form.Item>{getFieldDecorator("sql")(<Input.TextArea style={{width: "390px", height: "200px"}} />)}</Form.Item>
        return (
          <Form.Item label={locale['label.sourceQuery']}>
            <Popover placement="topLeft" title={locale['label.sourceQuery']} trigger="click" content={textarea}
                onVisibleChange={method.setQuery}>
              {getFieldDecorator("sqlPlain", sqlProps)(<Input size="small" readOnly style={{width: "390px"}} />)}
            </Popover>
          </Form.Item>
        );
      }
      return undefined
    },

    renderRcvSystem: () => {
      let type = form.getFieldValue('rcvSystemType')
      if (type === '1') {
        let fileProps = {initialValue: !item.fileCrudType ? '1' : item.fileCrudType}
        if (item.rcvSystemType !== '1') {
          let crud = form.getFieldValue('fileCrudType')
          item.fileCrudType = !crud ? item.fileCrudType : crud
        }
        
        return (
          <Form.Item label={locale['label.targetFileCRUD']}>
            {getFieldDecorator("fileCrudType", fileProps)(<Select size={"small"} className="size-id">
              {method.renderOpts("fileCrudType")}
            </Select>)}
          </Form.Item>
        );
      } else if (type === '2') {
        let dbProps = {initialValue: !item.dbCrudType ? '1' : item.dbCrudType}
        if (item.rcvSystemType !== '2') {
          let crud = form.getFieldValue('dbCrudType')
          item.dbCrudType = !crud ? item.dbCrudType : crud
        }
        
        return (
          <Form.Item label={locale['label.targetDBCRUD']}>
            {getFieldDecorator("dbCrudType", dbProps)(<Select size={"small"} className="size-name">
              {method.renderOpts("dbCrudType")}
            </Select>)}
          </Form.Item>
        );
      }
      return undefined
    },

    renderDataMap: () => {
      let useDataMap = form.getFieldValue('dataMapYN')
      if (useDataMap) {
        let reqProps = {initialValue: props.item.reqDataMappingId}
        let resProps = {initialValue: props.item.resDataMappingId}
        /*
          <div>
            <Form.Item label="Request">
              {getFieldDecorator("reqDataMappingId", reqProps)(<Input.Search size="small" readOnly
                onSearch={vars => { method.setDataMap('req') }} onClick={e => { method.editDataMap('req', e) }} className="size-id" />)}
            </Form.Item>
            <Form.Item label="Response">
              {getFieldDecorator("resDataMappingId", resProps)(<Input.Search size="small" readOnly
                onSearch={vars => { method.setDataMap('res') }} onClick={e => { method.editDataMap('res', e) }} className="size-id" />)}
            </Form.Item>
          </div>
        */
        return (
          <div>
            <Form.Item label={locale['label.request']}>
              {getFieldDecorator("reqDataMappingId", reqProps)(<Input size="small" readOnly allowClear
                onClick={e => { method.editDataMap('req', e) }} className="size-id" />)}
            </Form.Item>
            <Form.Item label={locale['label.response']}>
              {getFieldDecorator("resDataMappingId", resProps)(<Input size="small" readOnly allowClear
                onClick={e => { method.editDataMap('res', e) }} className="size-id" />)}
            </Form.Item>
          </div>
        );
      }
      return undefined
    },
  }
  
  let serviceTitle = (type) => {
    let sysType = '3'
    if (type === 'send') {
      sysType = form.getFieldValue('sendSystemType')
      switch (sysType) {
        case '1': return locale['label.sourceFile']
        case '2': return locale['label.sourceTable']
        default: return locale['label.sourceService']
      }
    } else if (type === 'rcv') {
      sysType = form.getFieldValue('rcvSystemType')
      switch (sysType) {
        case '1': return locale['label.targetFile']
        case '2': return locale['label.targetTable']
        default: return locale['label.targetService']
      }
    }
    return 'Service'
  }

  return (
    <div className="urm-editor">
      <div className="editor-buttons">
        <Button onClick={method.clickSave} disabled={!props.isPageSave()}>{locale['label.save']}</Button>
      </div>
      <Form colon={false}>
        <div className="row">
          <Form.Item label={locale['label.requestId']}>{getFieldDecorator("id")(<Input size="small" className="size-id" readOnly />)}</Form.Item>
          <Form.Item label={locale['label.requestName']}>{getFieldDecorator("name")(<Input size="small" className="size-name" />)}</Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.interfaceType']}>
            {getFieldDecorator("interfaceType", {initialValue: "1"})(<Select size={"small"} className="size-id">
              {method.renderOpts("infType")}
            </Select>)}
          </Form.Item>
          <Form.Item label={locale['label.processStatus']}>
            {getFieldDecorator("processStat", {initialValue: "1"})(<Select size={"small"} style={{width: "150px"}}>
              {method.renderOpts("procStat")}
            </Select>)}
          </Form.Item>
          <Form.Item label={locale['label.changeStatus']}>
            {getFieldDecorator("chgStat", {initialValue: "1"})(<Select size={"small"} className="size-id">
              {method.renderOpts("chgStat")}
            </Select>)}
          </Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.syncType']}>
            {getFieldDecorator("syncType", {initialValue: "1"})(<Select size={"small"} className="size-id">
              {method.renderOpts("syncType")}
            </Select>)}
          </Form.Item>
          <Form.Item label={locale['label.interfaceId']}>{getFieldDecorator("interfaceId")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.eaiYn']}>{getFieldDecorator("eaiYN", {valuePropName: "checked", initialValue: true})(<Switch size="small" />)}</Form.Item>
          <Form.Item label={locale['label.2pcYn']}>{getFieldDecorator("tpcYN", {valuePropName: "checked", initialValue: false})(<Switch size="small" />)}</Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.jobType']}>{getFieldDecorator("jobType")(<Input size="small" className="size-id" />)}</Form.Item>
          <Form.Item label={locale['label.trType']}>
            {getFieldDecorator("trType", {initialValue: "2"})(<Radio.Group >
              <Radio value="1">OneWay</Radio>
              <Radio value="2">BothWay</Radio>
            </Radio.Group>)}
          </Form.Item>
        </div>
        <div className="row">
          <Form.Item label={locale['label.testDate']}>{getFieldDecorator("testDate", {
            initialValue: [moment(), moment().add(7, 'd')]
          })(<RangePicker size="small" allowClear={false} className="size-name" />)}</Form.Item>
          <Form.Item label={locale['label.isMapping']}>{getFieldDecorator("dataMapYN", {valuePropName: "checked", initialValue: false})(<Checkbox />)}</Form.Item>
          {method.renderDataMap()}
        </div>
        <hr/>
        <div className="row">
          <div className="col-1">
            <div className="row">
              <Form.Item label={locale['label.sourceMethod']}>
                {getFieldDecorator("sendSystemType", {initialValue: "3"})(<Select size={"small"} className="size-id">
                  {method.renderOpts("sysType")}
                </Select>)}
              </Form.Item>
              <Form.Item label={locale['label.sourceSystem']}>
                {getFieldDecorator("sendSystemName")(<Input.Search size="small" readOnly onSearch={vars => { method.setSystem('send') }} className="size-id" />)}
              </Form.Item>
            </div>
            <div className="row">
              <Form.Item label={serviceTitle('send')}>{getFieldDecorator("sendServerName")(<Input size="small" className="size-id" />)}</Form.Item>
              <Form.Item label={locale['label.sourceInfo']}>{getFieldDecorator("sendDbInfo")(<Input size="small" className="size-id" />)}</Form.Item>
            </div>
            <div className="row">
              {method.renderSendSystem()}
            </div>
            <div className="row">
              <Form.Item label={locale['label.sndJobCode']}>
                {getFieldDecorator("sendJobCodeName")(<Input.Search size="small" readOnly className="size-id" onSearch={vars => { method.setBizCode('send') }} />)}
              </Form.Item>
              <Form.Item label={locale['label.sourceAdmin']}>
                {getFieldDecorator("sendAdminName")(<Input.Search size="small" readOnly className="size-id" onSearch={vars => { method.setUser('send') }} />)}
              </Form.Item>
            </div>
          </div>
          <div className="col-1">
            <div className="row">
              <Form.Item label={locale['label.targetMethod']}>
                {getFieldDecorator("rcvSystemType", {initialValue: "3"})(<Select size={"small"} className="size-id">
                  {method.renderOpts("sysType")}
                </Select>)}
              </Form.Item>
              <Form.Item label={locale['label.targetSystem']}>
                {getFieldDecorator("rcvSystemName")(<Input.Search size="small" readOnly onSearch={vars => { method.setSystem('rcv') }} className="size-id" />)}
              </Form.Item>
            </div>
            <div className="row">
              <Form.Item label={serviceTitle('rcv')}>{getFieldDecorator("rcvServerName")(<Input size="small" className="size-id" />)}</Form.Item>
              <Form.Item label={locale['label.targetInfo']}>{getFieldDecorator("rcvDbInfo")(<Input size="small" className="size-id" />)}</Form.Item>
            </div>
            <div className="row">
              {method.renderRcvSystem()}
            </div>
            <div className="row">
              <Form.Item label={locale['label.rcvJobCode']}>
                {getFieldDecorator("rcvJobCodeName")(<Input.Search size="small" readOnly className="size-id" onSearch={vars => { method.setBizCode('rcv') }} />)}
              </Form.Item>
              <Form.Item label={locale['label.targetAdmin']}>
                {getFieldDecorator("rcvAdminName")(<Input.Search size="small" readOnly className="size-id" onSearch={vars => { method.setUser('rcv') }} />)}
              </Form.Item>
            </div>
          </div>
        </div>
        <hr/>
        <div className="row">
          <Form.Item label={locale['label.etcRequest']} className="col-1">{getFieldDecorator("etcRemark")(<Input.TextArea className="urm-remark" />)}</Form.Item>
          <Form.Item label={locale['label.eaiRequest']} className="col-1">{getFieldDecorator("eaiRemark")(<Input.TextArea className="urm-remark" />)}</Form.Item>
        </div>
        <hr/>
        <div className="row">
          <Form.Item label={locale['label.attachmentFile']}>
            {getFieldDecorator('infFileName', {
              valuePropName: 'file', getValueFromEvent: method.uploadFile
            })(<Upload beforeUpload={method.preventAction} className="urm-upload">
              <Button icon="select" size="small" />
            </Upload>)}
          </Form.Item>
        </div>
      </Form>
      
      <SubModal ref={(list) => { sysList = list }} width="1120px">
        <SystemList key="list" path="system" codeList={props.codeList} onlySearch={true} />
      </SubModal>
      
      <SubModal ref={(list) => { bizList = list }} width="1215px">
        <BizList key="list" onlySearch={true} />
      </SubModal>
      
      <SubModal ref={(list) => { usrList = list }} width="980px">
        <UserList key="list" path="user" authList={props.authList} onlySearch={true} />
      </SubModal>
      
      <SubModal ref={(list) => { mapList = list }} width="1030px">
        <DataMapList key="list" path="datamap" />
      </SubModal>
      
      <DataMapEditor ref={(map) => { dataMap = map }} path="datamap" codeList={props.codeList} onlySearch={true} />
    </div>
  );
}

const WrappedRequestEditor = Form.create({name:'request_editor'})(RequestEditorForm)
export default RequestEditor

// vue-front/src/components/rule/editor/RequestEditor.vue
<template>
  <div class="urm-editor">
    <div class="editor-buttons">
      <el-button @click="clickSave" plain>{{$t('label.save')}}</el-button>
    </div>
    <el-form label-width="135px">
      <div class="row">
        <el-form-item :label="$t('label.requestId')">
          <el-input v-model="item.id" class="size-id" readonly/>
        </el-form-item>
        <el-form-item :label="$t('label.requestName')">
          <el-input v-model="item.name" class="size-name"/>
        </el-form-item>
      </div>

      <div class="row">
        <el-form-item :label="$t('label.interfaceType')">
          <el-select v-model="item.interfaceType" class="size-id" @change="handleChangeInfType">
            <el-option v-for="type in infTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('label.processStatus')">
          <el-select v-model="item.processStat" class="size-id">
            <el-option v-for="stat in procStats" :value="stat.code" :label="stat.name" :key="stat.code"/>
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('label.changeStatus')">
          <el-select v-model="item.chgStat" class="size-id">
            <el-option v-for="stat in chgStats" :value="stat.code" :label="stat.name" :key="stat.code"/>
          </el-select>
        </el-form-item>
      </div>

      <div class="row">
        <el-form-item :label="$t('label.syncType')">
          <el-select v-model="item.syncType" class="size-id" @change="handleChangeSyncType">
            <el-option v-for="type in syncTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('label.interfaceId')">
          <el-input v-model="item.interfaceId" class="size-id"/>
        </el-form-item>
        <el-form-item :label="$t('label.eaiYn')">
          <el-checkbox v-model="item.eaiYN"/>
        </el-form-item>
        <el-form-item :label="$t('label.2pcYn')">
          <el-checkbox v-model="item.tpcYN"/>
        </el-form-item>
      </div>

      <div class="row">
        <el-form-item :label="$t('label.jobType')">
          <el-input v-model="item.jobType" class="size-id" />
        </el-form-item>
        <el-form-item :label="$t('label.trType')">
          <el-radio-group v-model="item.trType">
            <el-radio v-for="type in trTypes" :label="type.code" :key="type.code">{{type.name}}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item :label="$t('label.testDate')">
          <el-date-picker v-model="item.testDate" type="daterange"
            start-placeholder="Start Date" end-placeholder="End Date" class="size-name"/>
        </el-form-item>
      </div>

      <div class="row">
        <el-form-item :label="$t('label.isMapping')">
          <el-checkbox v-model="item.dataMapYN"/>
        </el-form-item>
        <el-form-item label="Request" v-if="item.dataMapYN">
          <el-input v-model="item.reqDataMappingId" class="size-id" readonly>
            <i slot="suffix" class="el-input__icon el-icon-close"></i>
          </el-input>
        </el-form-item>
        <el-form-item label="Response" v-if="item.dataMapYN">
          <el-input v-model="item.resDataMappingId" class="size-id" readonly>
            <i slot="suffix" class="el-input__icon el-icon-close"></i>
          </el-input>
        </el-form-item>
      </div>
      <hr/>
      <div class="row">
        <div class="col-1">
          <div class="row">
            <el-form-item :label="$t('label.sourceMethod')">
              <el-select v-model="item.sendSystemType" class="size-id">
                <el-option v-for="type in sysTypes" :value="type.code" :label="type.name" :key="type.code"/>
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('label.sourceSystem')">
              <el-input v-model="item.sendSystem.name" class="size-id" @click.native="showSystemList('send')" readonly/>
            </el-form-item>
          </div>
          <div class="row">
            <el-form-item :label="serviceLabel('send')">
              <el-input v-model="item.sendServerName" class="size-id" />
            </el-form-item>
            <el-form-item :label="$t('label.sourceInfo')">
              <el-input v-model="item.sendDbInfo" class="size-id" />
            </el-form-item>
          </div>
          <!-- DB -->
          <div class="row" v-if="item.sendSystemType === '2'">
            <el-form-item :label="$t('label.sourceQuery')">
              <el-input v-model="item.sqlPlain" style="width: 390px;" readonly/>
            </el-form-item>
          </div>
          <div class="row">
            <el-form-item :label="$t('label.sndJobCode')">
              <el-input v-model="jobCodeName.send" class="size-id" readonly/>
            </el-form-item>
            <el-form-item :label="$t('label.sourceAdmin')">
              <el-input v-model="adminName.send" class="size-id" @click.native="showUserList('send')" readonly/>
            </el-form-item>
          </div>
        </div>

        <div class="col-1">
          <div class="row">
            <el-form-item :label="$t('label.targetMethod')">
              <el-select v-model="item.rcvSystemType" class="size-id">
                <el-option v-for="type in sysTypes" :value="type.code" :label="type.name" :key="type.code"/>
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('label.targetSystem')">
              <el-input v-model="item.rcvSystem.name" class="size-id" @click.native="showSystemList('rcv')" readonly/>
            </el-form-item>
          </div>
          <div class="row">
            <el-form-item :label="serviceLabel('rcv')">
              <el-input v-model="item.rcvServerName" class="size-id" />
            </el-form-item>
            <el-form-item :label="$t('label.targetInfo')">
              <el-input v-model="item.rcvDbInfo" class="size-id" />
            </el-form-item>
          </div>
          <!-- File -->
          <div class="row" v-if="item.rcvSystemType === '1'">
            <el-form-item :label="$t('label.targetFileCRUD')">
              <el-select v-model="item.fileCrudType" class="size-id">
                <el-option v-for="type in fileCrudTypes" :value="type.code" :label="type.name" :key="type.code"/>
              </el-select>
            </el-form-item>
          </div>
          <!-- DB -->
          <div class="row" v-if="item.rcvSystemType === '2'">
            <el-form-item :label="$t('label.targetDBCRUD')">
              <el-select v-model="item.dbCrudType" class="size-name">
                <el-option v-for="type in dbCrudTypes" :value="type.code" :label="type.name" :key="type.code"/>
              </el-select>
            </el-form-item>
          </div>
          <div class="row">
            <el-form-item :label="$t('label.rcvJobCode')">
              <el-input v-model="jobCodeName.rcv" class="size-id" readonly/>
            </el-form-item>
            <el-form-item :label="$t('label.targetAdmin')">
              <el-input v-model="adminName.rcv" class="size-id" @click.native="showUserList('rcv')" readonly/>
            </el-form-item>
          </div>
        </div>
      </div>

      <hr/>
      <div class="row">
        <el-form-item :label="$t('label.etcRequest')">
          <el-input type="textarea" v-model="item.etcRemark"/>
        </el-form-item>
        <el-form-item :label="$t('label.eaiRequest')">
          <el-input type="textarea" v-model="item.eaiRemark"/>
        </el-form-item>
      </div>

      <hr/>
      <div class="row">
        <el-form-item :label="$t('label.attachmentFile')">
          <el-input v-model="item.infFileName" @click.native="changeInfFile"/>
          <input type="file" ref="infFile" @change="handleChangeInfFile" style="display: none;"/>
        </el-form-item>
      </div>
    </el-form>

    <el-dialog :visible.sync="systemListShow" width="1300px" top="8vh" append-to-body :close-on-click-modal="false">
      <SystemList ref="sysList" :onlySearch="true" :sysTypes="sysTypes" @row-dblclick="cbSystemRowClick"/>
    </el-dialog>

    <el-dialog :visible.sync="userListShow" width="1080px" top="8vh" append-to-body :close-on-click-modal="false">
      <UserList ref="usrList" :onlySearch="true" @row-dblclick="cbUserRowClick"/>
    </el-dialog>
  </div>
</template>

<script>
import RuleEditor from './RuleEditor'
import RuleUtil from '@/components/rule/RuleUtil'
import UserList from '@/components/manage/list/UserList'

export default {
  mixins: [RuleEditor],
  props: {
    infTypes: {
      type: Array,
      default: function () {
        return []
      },
    },
    chgStats: {
      type: Array,
      default: function () {
        return []
      },
    },
    procStats: {
      type: Array,
      default: function () {
        return []
      },
    },
  },
  components: {
    UserList,
  },
  data() {
    return {
      tgtType: '',
      systemListShow: false,
      userListShow: false,
    }
  },
  methods: {
    customValidator () {
      let item = this.item
      if (!item.sendSystemId || item.sendSystemId.trim().length === 0) {
        this.$message({message: this.$t('message.1008'), type: 'warning'})
        return false
      }
      if (!item.rcvSystemId || item.rcvSystemId.trim().length === 0) {
        this.$message({message: this.$t('message.1009'), type: 'warning'})
        return false
      }
      if (!item.sendJobCodeId || item.sendJobCodeId.trim().length === 0) {
        this.$message({message: this.$t('message.1019'), type: 'warning'})
        return false
      }
      if (!item.rcvJobCodeId || item.rcvJobCodeId.trim().length === 0) {
        this.$message({message: this.$t('message.1019'), type: 'warning'})
        return false
      }

      if (!item.sendAdminId || item.sendAdminId.trim().length === 0) {
        //item.sendAdminId = this.props.userInfo.id
      }
      if (!item.rcvAdminId || item.rcvAdminId.trim().length === 0) {
        //item.rcvAdminId = this.props.userInfo.id
      }

      if (item.sendSystemType !== '2') {
        item.sqlPlain = null
        item.sql = null
      }
      if (item.rcvSystemType !== '1') {
        item.fileCrudType = null
      }
      if (item.rcvSystemType !== '2') {
        item.dbCrudType = null
      }

      /*if( !urmsc.isSelectAuth('prcStat', data.processStat, this.props.userInfo.auth) ) {
        message.warning(locale['message.1010']);
        return false
      }
      if( !urmsc.isSelectAuth('chgStat', data.chgStat, this.props.userInfo.auth) ) {
        message.warning('\'변경 신청\' 으로 수정합니다.');
        this.setState({ item: {...this.state.item, chgStat: 0} })
        return false
      }*/
      return true
    }, // customValidator

    handleChangeInfType (val) {
      switch (val) {
        case '1':
          this.item.sendSystemType = '3'
          this.item.rcvSystemType = '3'
          this.item.tpcYN = false
          this.item.trType = '2'
          this.item.dataMapYN = false
          break
        case '2':
          this.item.sendSystemType = '3'
          this.item.rcvSystemType = '3'
          this.item.tpcYN = true
          this.item.dataMapYN = false
          break
        case '3':
          this.item.sendSystemType = '3'
          this.item.rcvSystemType = '3'
          this.item.tpcYN = true
          this.item.dataMapYN = true
          break
      }
    }, // handleChangeInfType

    handleChangeSyncType (val) {
      switch (val) {
        case '2':
          this.item.trType = '1'
          break
        default:
          this.item.trType = '2'
          break
      }
    }, // handleChangeSyncType

    changeInfFile () {
      this.$refs.infFile.click()
    }, // changeInfFile

    handleChangeInfFile (e) {
      const loading = this.$startLoading()
      let file = e.target.files[0]

      let formData = new FormData()
      formData.append('file', file, file.name)

      let url = '/api/request/upload'
      this.$http({
        method : 'POST',
        url: url,
        data: formData,
      }).then(response => {
        let res = response.data
        this.$message({message: this.$t('message.0007') + ' - ' + res, type: 'success'})
        this.item.infFileName = e.target.file.name
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // handleChangeInfFile

    showSystemList (type) {
      this.tgtType = type
      this.systemListShow = true
    }, // showSystemList

    cbSystemRowClick (row) {
      if (this.tgtType === 'send') {
        this.item.sendSystemId = row.id
        this.item.sendSystem.name = row.name
      } else if (this.tgtType === 'rcv') {
        this.item.rcvSystemId = row.id
        this.item.rcvSystem.name = row.name
      }
      this.systemListShow = false
    }, // cbSystemRowClick
    
    showUserList (type) {
      this.tgtType = type
      this.userListShow = true
    }, // showUserList

    cbUserRowClick (row) {
      if (this.tgtType === 'send') {
        this.item.sendAdminId = row.id
        this.item.sendAdmin.name = row.name
        this.item.sendAdmin.positionName = (row.positionName ? row.positionName : '--')
      } else if (this.tgtType === 'rcv') {
        this.item.rcvAdminId = row.id
        this.item.rcvAdmin.name = row.name
        this.item.rcvAdmin.positionName = (row.positionName ? row.positionName : '--')
      }
      this.userListShow = false
    }, // cbUserRowClick
  },
  computed: {
    syncTypes: function () {
      let kind = RuleUtil.CODEKEY.syncType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    trTypes: function () {
      let kind = RuleUtil.CODEKEY.trType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    sysTypes: function () {
      let kind = RuleUtil.CODEKEY.sysType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    dbCrudTypes: function () {
      let kind = RuleUtil.CODEKEY.dbCrudType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    fileCrudTypes: function () {
      let kind = RuleUtil.CODEKEY.fileCrudType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    serviceLabel () {
      return (type) => {
        if (type === 'send') {
          switch (this.item.sendSystemType) {
            case '1': return this.$t('label.sourceFile')
            case '2': return this.$t('label.sourceTable')
            default: return this.$t('label.sourceService')
          }
        } else if (type === 'rcv') {
          switch (this.item.rcvSystemType) {
            case '1': return this.$t('label.targetFile')
            case '2': return this.$t('label.targetTable')
            default: return this.$t('label.targetService')
          }
        }
      }
    },
    jobCodeName: function () {
      return {
        send: this.item.sendJobCode.part2Name + '(' + this.item.sendJobCode.part2Id + ')',
        rcv: this.item.rcvJobCode.part2Name + '(' + this.item.rcvJobCode.part2Id + ')',
      }
    },
    adminName: function () {
      return {
        send: this.item.sendAdmin.name + '(' + this.item.sendAdmin.positionName + ')',
        rcv: this.item.rcvAdmin.name + '(' + this.item.rcvAdmin.positionName + ')',
      }
    },
  },
}
</script>
