// react-front/src/component/rule/editor/sub/CopyData.jsx
import React from 'react'
import { Button, Table } from 'antd'
import { Form, Input, Select } from 'antd'
import moment from 'moment'

import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class CopySearch extends React.Component {
  componentDidMount() {
    this.props.search()
  }
  
  method = {
    clickSearch: e => {
      this.props.search(this.props.form.getFieldsValue())
    },
    
    renderOpts: (key) => {
      return urmsc.getSubListByKey(this.props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.dataId']}>{getFieldDecorator("id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.dataName']}>{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
            <Form.Item label={locale['label.dataType']}>
              {getFieldDecorator("type", {initialValue: ""})(<Select size="small" className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("dataType")}
              </Select>)}
            </Form.Item>
            <Form.Item className="search-buttons">
              <Button icon="search" onClick={this.method.clickSearch} title={locale['label.search']} />
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

class CopyList extends React.Component {
  state = {
    items: [],
    fields: [],
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.items !== nextState.items) {
      return true
    }
    if (this.state.fields !== nextState.fields) {
      return true
    }
    return false
  }

  method = {
    getTypeStr: (kind, key) => {
      let obj = {}
      let list = this.props.codeList
      for(let i=0; i < list.length; i++) {
        let it = list[i]
        if (it.kind === kind && it.code === key) {
          obj = it
          break
        }
      }
      return obj.name
    },
    
    getFieldStr: (kind, key) => {
      if (kind === 'type') {
        switch (key) {
        case 'C': return 'Character'
        case 'N': return 'Number'
        case 'D': return 'Date'
        case 'B': return 'Binary'
        default: return '' 
        }
      } else if (kind === 'yn') {
        switch (key) {
        case true: return 'Yes'
        case false: return 'No'
        default: return '' 
        }
      }
    },

    search: (param) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/data',
        data: param,
        success: function(list) {
          $this.setState({items: list})
        },
      })
    },
    
    viewFields: (record) => {
      let $this = this
      urmsc.ajax({
        type: 'GET',
        url: 'api/data/field/' + record.id,
        success: function(fields) {
          $this.setState({fields: (fields ? fields : [])})
        }
      })
    }
  }

  render() {
    return (
      <div className="urm-list">
        <WrappedCopySearch  {...this.props} search={this.method.search} />
        <Table className="table-striped"
          dataSource={this.state.items} pagination={false} bordered
          size="small" scroll={{ y: 300 }} rowKey="id"
          onRow={(record, index) => {
            return {
              onClick: e => { this.method.viewFields(record) },
              onDoubleClick: e => { if (this.props.onDbClick) this.props.onDbClick(record) }
            }
          }
        }>
          <Table.Column title={locale['label.id']} dataIndex="id" width="150px"/>
          <Table.Column title={locale['label.name']} dataIndex="name" width="250px"/>
          <Table.Column title={locale['label.dataType']} dataIndex="type" render={(val) => ( this.method.getTypeStr('dataType', val) )} />
          <Table.Column title={locale['label.registId']} dataIndex="regId"/>
          <Table.Column title={locale['label.registDate']} dataIndex="regDate" render={(val) => ( moment(val).format('YYYY-MM-DD HH:mm') )} />
        </Table>
        
        <hr />
        
        <Table className="table-striped"
          dataSource={this.state.fields} pagination={false} bordered
          size="small" scroll={{ y: 300 }} rowKey="sno">
          <Table.Column title={locale['label.index']} dataIndex="sno" width="65px" align="center"/>
          <Table.Column title={locale['label.fieldName']} dataIndex="engName" width="150px"/>
          <Table.Column title={locale['label.fieldLocalName']} dataIndex="name" width="150px"/>
          <Table.Column title={locale['label.fieldType']} dataIndex="type" width="110px" render={(val) => ( this.method.getFieldStr('type', val) )}/>
          <Table.Column title={locale['label.dFormat']} dataIndex="dateFormat"/>
          <Table.Column title={locale['label.len']} dataIndex="length"/>
          <Table.Column title={locale['label.nullable']} dataIndex="nullable" width="75px" render={(val) => ( this.method.getFieldStr('yn', val) )}/>
          <Table.Column title={locale['label.isKey']} dataIndex="keyYN" width="85px" render={(val) => ( this.method.getFieldStr('yn', val) )}/>
          <Table.Column title={locale['label.isSQL']} dataIndex="sqlYN" width="110px" render={(val) => ( this.method.getFieldStr('yn', val) )}/>
        </Table>
      </div>
    );
  }
}

const WrappedCopySearch = Form.create({name:'copy_search'})(CopySearch)
export default CopyList

// vue-front/src/components/rule/editor/data/CopyData.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.dataId')">
          <el-input v-model="sparam.id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.dataName')">
          <el-input v-model="sparam.name" class="search-name" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.dataType')">
          <el-select v-model="sparam.type" class="search-id" @change="search">
            <el-option value="" label="ALL"/>
            <el-option v-for="type in dataTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
      </div>
    </div>

    <el-table :data="items" @row-dblclick="handleRowDblclick" height="300" border class="table-striped">
      <el-table-column :label="$t('label.id')" prop="id" width="150"/>
      <el-table-column :label="$t('label.name')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.dataType')" width="100">
        <template slot-scope="scope">
          <span>{{getTypeStr('dataType', scope.row.type)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.registId')" prop="regId" width="200" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.registDate')" width="200">
        <template slot-scope="scope">
          <span>{{scope.row.regDate}}</span>
        </template>
      </el-table-column>
      <el-table-column width="45" class-name="edit-cell operations">
        <template slot-scope="scope">
          <el-button icon="el-icon-edit" @click.stop="viewFields(scope.row.id)"/>
        </template>
      </el-table-column>
    </el-table>

    <hr/>
    <el-table :data="fields">
      <el-table-column :label="$t('label.index')" prop="sno" width="70" align="center"/>
      <el-table-column :label="$t('label.fieldName')" prop="engName" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.fieldLocalName')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.fieldType')" width="85">
        <template slot-scope="scope">
          <span>{{getTypeStr(scope.row.type)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.dFormat')" prop="dateFormat" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.len')" prop="length" width="70"/>
      <el-table-column :label="$t('label.nullable')" width="75">
        <template slot-scope="scope">
          <span>{{getYNStr(scope.row.nullable)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.isKey')" width="85">
        <template slot-scope="scope">
          <span>{{getYNStr(scope.row.keyYN)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.isSQL')" width="110">
        <template slot-scope="scope">
          <span>{{getYNStr(scope.row.sqlYN)}}</span>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>
<script>
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  data () {
    return {
      sparam: {
        type: '',
      },
      items: [],
      fields: [],
    }
  },
  methods: {
    search() {
      const loading = this.$startLoading()
      this.$http.get('/api/data', {
        params: this.sparam,
      }).then(response => {
        this.items = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // search

    viewFields (id) {
      const loading = this.$startLoading()
      this.$http.get('/api/data/field/' + id, {
      }).then(response => {
        this.fields = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // handleRowClick

    handleRowDblclick (row) {
      const loading = this.$startLoading()
      this.$http.get('/api/data/field/' + row.id, {
      }).then(response => {
        this.$emit('confirm', response.data)
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // handleRowDblclick

    getTypeStr (val) {
      switch (val) {
        case 'C': return 'Character'
        case 'N': return 'Number'
        case 'D': return 'Date'
        case 'B': return 'Binary'
      }
    }, // getTypeStr

    getYNStr (val) {
      return val ? 'Yes' : 'No'
    }, // getTypeStr
  },
  mounted () {
    this.search()
  },
  computed: {
    dataTypes: function () {
      let kind = RuleUtil.CODEKEY.dataType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
  },
}
</script>
