// react-front/src/component/rule/editor/sub/ExcelData.jsx
import React, { useState } from 'react'
import { Button, Modal } from 'antd'
import { Form, Input, Select, Upload } from 'antd'

import EditableField from './EditableField'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class ExcelEditor extends React.Component {
  state = {
    visible: false,
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (this.state.visible !== nextState.visible) {
      return true
    }
    return false
  }

  method = {
    handleCancel: e => {
      this.setState({visible: false})
    },
  }

  childMethod = {
    confirm: (fields) => {
      console.log(fields)
    },
  }

  render() {
    return (
      <Modal visible={this.state.visible} width="1000px"
        footer={null} onCancel={this.method.handleCancel} className="urm-modal">
        <WrappedExcelEditor {...this.childMethod} />
      </Modal>
    );
  }
}

const ExcelEditorForm = (props) => {
  const { form } = props
  const { getFieldDecorator } = props.form
  const [ fields, setFields ] = useState([])

  let method = {
    clickConfirm: e => {
      let saveItem = method.makeFieldObj()
      props.confirm(saveItem)
    },
    
    makeFieldObj: () => {
      let saveItem = [...fields]
      
      let fieldForm = form.getFieldValue('fields')
      saveItem.forEach((it, idx) => {
        let field = fieldForm[idx]
        for (let key in field) {
          if (key.endsWith('YN') || key === 'nullable') {
            it[key] = urmsc.convertYN(field[key])
          } else {
            it[key] = (key in field) ? field[key] : it[key]
          }
        }
      })
      
      return saveItem
    },
    
    preventAction: (file) => {
      return false
    },
    
    uploadFile: e => {
      return e && e.file
    },
    
    getFields: e => {
      // application/vnd.openxmlformats-officedocument.spreadsheetml.sheet : xlsx
      let file = form.getFieldValue('fileName')
      let sheetName = form.getFieldValue('sheetName')
      
      if (!sheetName || sheetName.trim().length === 0) {
        return false
      }
      
      let formData = new FormData();
      formData.append('sheetName', encodeURIComponent(sheetName))
      formData.append('file', file, file.name)
      
      urmsc.ajax({
        type: 'POST',
        url: 'api/data/field/excel',
        data: formData,
        contentType: false,
        success: function(res) {
          setFields(res)
        }
      })
    },
    
    renderYesOrNo: (val, dataIndex) => {
      return (
        <Form.Item>{getFieldDecorator(dataIndex, {initialValue: urmsc.convertYN(val)})(
          <Select size="small">
            <Select.Option key="y" value="Y">Yes</Select.Option>
            <Select.Option key="n" value="N">No</Select.Option>
          </Select>)}
        </Form.Item>
      );
    },
  }

  return (
    <div className="urm-editor">
      <div className="editor-buttons">
        <Button onClick={method.clickConfirm}>{locale['label.confirm']}</Button>
      </div>
      <Form colon={false}>
        <div className="row">
          <Form.Item label={locale['label.fileName']}>
            {getFieldDecorator('fileName', {
              valuePropName: 'file', getValueFromEvent: method.uploadFile
            })(<Upload beforeUpload={method.preventAction} className="urm-upload" accept="application/vnd.ms-excel">
              <Button icon="select" size="small" />
            </Upload>)}
          </Form.Item>
          <Form.Item label={locale['label.fileSelect']}>{getFieldDecorator("sheetName")(<Input size="small" style={{width: "220px"}} />)}</Form.Item>
          <Form.Item><Button icon="upload" size="small" onClick={method.getFields} title={locale['label.excelUpload']} /></Form.Item>
        </div>
        
        <hr />
        
        <EditableField form={props.form} item={fields} />
      </Form>
    </div>
  );
}

const WrappedExcelEditor = Form.create({name:'excel_editor'})(ExcelEditorForm)
export default ExcelEditor

// vue-front/src/components/rule/editor/data/ExcelData.vue
<template>
  <div class="urm-editor">
    <div class="editor-buttons">
      <el-button @click="clickConfirm">{{$t('label.confirm')}}</el-button>
    </div>
    <el-form :inline="true">
      <el-form-item :label="$t('label.fileName')">
        <el-input v-model="fileName" @click.native="changeXlFile" readonly/>
        <input type="file" ref="xlFile" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
          @change="handleChangeXlFile" style="display: none;"/>
      </el-form-item>
      <el-form-item :label="$t('label.fileSelect')">
        <el-input v-model="sheetName" class="size-name"/>
      </el-form-item>
      <el-form-item label="">
        <el-button icon="el-icon-upload" @click.stop="getFields"/>
      </el-form-item>
    </el-form>
    <FieldTable :data="fields" :isTemplate="true"/>
  </div>
</template>
<script>
import FieldTable from './FieldTable'

export default {
  components: {
    FieldTable,
  },
  data () {
    return {
      fileName: '',
      sheetName: '',
      fields: [],
    }
  },
  methods: {
    clickConfirm () {
      this.$emit('confirm', this.fields)
    }, // clickConfirm

    getFields () {
      let files = this.$refs.xlFile.files
      if (files.length === 0) {
        return false
      }
      let sheetName = this.sheetName
      if (!sheetName || sheetName.trim().length === 0) {
        return false
      }

      let formData = new FormData()
      formData.append('sheetName', encodeURIComponent(sheetName))
      formData.append('file', files[0], files[0].name)

      const loading = this.$startLoading()
      this.$http({
        method : 'POST',
        url: '/api/data/field/excel',
        data: formData,
      }).then(response => {
        this.fields = response.data
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }, // getFields

    changeXlFile () {
      this.$refs.xlFile.click()
    }, // changeFile

    handleChangeXlFile (e) {
      this.fileName = e.target.files[0].name
    }, // handleChangeFile
  },
}
</script>
