// vue-front/src/components/process/log/list/RealtimeMessageList.vue
<template>
  <div class="urm-list">
    <el-table :data="data" border stripe>
      <el-table-column label="Index" prop="messageIndex" width="65"/>
      <el-table-column label="필드명" prop="fieldName"/>
      <el-table-column label="값" width="400" class="edit-cell">
        <template slot-scope="scope">
          <el-input v-model="scope.row.fieldValue" readonly/>
        </template>
      </el-table-column>
    </el-table>

    <hr/>
    <el-input type="textarea" v-model="message" readonly/>
  </div>
</template>
<script>
export default {
  props: {
    data: {
      type: Array,
      default: () => [],
    },
  },
  computed: {
    message: function () {
      let msg = ''
      if (this.data) {
        this.data.forEach((mf) => {
          msg += mf.fieldValue
        })
      }
      return msg
    },
  },
}
</script>

// react-front/src/components/process/log/list/RealtimeMessage-list.jsx
import React from 'react'
import { Table, Input } from 'antd'

export default class RealtimeMessageList extends React.Component {
  state = {
    items: [],
    msg: '',
  }

  render() {
    return (
      <div className="urm-list">
        <Table className="table-striped upper-list" scroll={{y: 400}}
            dataSource={this.state.items} pagination={false} bordered
            size="small" rowKey="messageIndex">
          <Table.Column title="Index" dataIndex="messageIndex" width="65px" />
          <Table.Column title="필드명" dataIndex="fieldName" />
          <Table.Column title="값" dataIndex="fieldValue" width="400px" render={(val) => ( <Input value={val} readOnly /> )} />
        </Table>

        <hr />

        <Input.TextArea value={this.state.msg} readOnly style={{height: 160}} />
      </div>
    );
  }
}
