// vue-front/src/components/statics/RequestChangeMonth.vue
<template>
  <div class="urm-pannel">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item label="일자 선택">
          <el-date-picker v-model="procDate" type="monthrange" value-format="yyyyMM" range-separator="~" style="width: 220px;"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
      </div>
    </div>
    <ChangeList ref="list" :items="listItem"/>
  </div>
</template>

<script>
import ChangeList from './list/RequestChangeList'

export default {
  computed: {
    procDate: {
      get: function () {
        return [this.sparam.startDate, this.sparam.endDate]
      },
      set: function (nVal) {
        this.sparam.startDate = nVal[0]
        this.sparam.endDate = nVal[1]
      }
    },
  },
  components: {
    ChangeList,
  },
  
  data () {
    return {
      path: '/api/stat/change/month',
      listItem: null,
      sparam: {
        type: '',
        startDate: '',
        endDate: '',
      }
    }
  },

  methods: {
    search() {
      const loading = this.$startLoading()
      this.$http.get(this.path, {
        params: this.sparam,
      }).then(response => {
        this.listItem = response.data
        console.log('response.data:' + response.data)
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }
  }
}
</script>

// react-front/src/components/statics/RequestChangeMonth.jsx
import React from 'react'
import { Form, DatePicker, Button } from 'antd'
import moment from 'moment'

import ChangeList from './list/RequestChange-list'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class MonthSearch extends React.Component {
  componentDidMount() {
    //this.props.search(this.method.makeParams())
  }

  method = {
    clickSearch: e => {
      this.props.search(this.method.makeParams())
    },
    
    makeParams: () => {
      let form = this.props.form
      let dates = form.getFieldValue('processDate')
      return {
        startDate: dates[0].format('YYYYMM'),
        endDate: dates[1].format('YYYYMM'),
      }
    },
  }

  render() {
    const { RangePicker } = DatePicker
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label="일자 선택">{getFieldDecorator("processDate", {
              initialValue: [moment(), moment()]
            })(<RangePicker size="small" style={{width: "220px"}} allowClear={false} format='YYYY-MM' mode={['month', 'month']} />)}</Form.Item>
            <Form.Item className="search-buttons">
              <Button size="small" onClick={this.method.clickSearch}>{locale['label.search']}</Button>
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

const WrappedMonthSearch = Form.create({name:'cmonth_search'})(MonthSearch)
export default class RequestChangeDay extends React.Component {
  method = {
    search: (params) => {
      let _this = this
      urmsc.ajax({
        type: 'GET',
        url: '/URM/api/stat/change/month',
        data: params,
        success: function(res) {
          _this.refs.list.setState({items: res})
        }
      })
    }
  }

  render() {
    return (
      <div className="urm-panel">
        <WrappedMonthSearch search={this.method.search} />
        <ChangeList ref="list" />
      </div>
    );
  }
}
