// vue-front/src/components/statics/RequestProcessMonth.vue
<template>
  <div class="urm-pannel">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.interfaceType')">
          <el-select v-model="sparam.type" class="search-id">
            <el-option value="" label="ALL"/>
            <el-option v-for="type in infTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
        <el-form-item label="일자 선택">
          <el-date-picker v-model="procDate" type="monthrange" value-format="yyyyMM" range-separator="~" style="width: 220px"/>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
      </div>
    </div>
    <ProcessList ref="list" :items="listItem"/>
  </div>
</template>

<script>
import ProcessList from './list/RequestProcessList'
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  computed: {
    infTypes: function () {
      let kind = RuleUtil.CODEKEY.infType
      return this.$store.state.codes.filter(code => (code.kind === kind))
    },
    procDate: {
      get: function () {
        return [this.sparam.startDate, this.sparam.endDate]
      },
      set: function (nVal) {
        this.sparam.startDate = nVal[0]
        this.sparam.endDate = nVal[1]
      }
    }
  },
  components: {
    ProcessList,
  },
  data () {
    return {
      path: '/api/stat/process/month',
      listItem: null,
      sparam: {
        type: '',
        startDate: '',
        endDate: '',
      },
    }
  },
  methods: {
    search() {
      const loading = this.$startLoading()
      this.$http.get(this.path, {
        params: this.sparam,
      }).then(response => {
        this.listItem = response.data
        console.log('response.data:' + response.data)
      }).catch(error => {
        this.$handleHttpError(error)
      }).finally(() => {
        loading.close()
      })
    }
  }
}
</script>

// react-front/src/components/statics/RequestProcessMonth.jsx
import React from 'react'
import { Form, Select, DatePicker, Button } from 'antd'
import moment from 'moment'

import ProcessList from './list/RequestProcess-list'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class MonthSearch extends React.Component {
  componentDidMount() {
    //this.props.search(this.method.makeParams())
  }

  method = {
    clickSearch: e => {
      this.props.search(this.method.makeParams())
    },
    
    makeParams: () => {
      let form = this.props.form
      let dates = form.getFieldValue('processDate')
      return {
        interfaceType: form.getFieldValue('interfaceType'),
        startDate: dates[0].format('YYYYMM'),
        endDate: dates[1].format('YYYYMM'),
      }
    },
    
    renderOpts: (key) => {
      return urmsc.getSubListByKey(this.props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
  }

  render() {
    const { RangePicker } = DatePicker
    const { getFieldDecorator } = this.props.form

    return (
      <div className="search-bar">
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.interfaceType']}>
              {getFieldDecorator("type", {initialValue: ""})(<Select size="small" className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("infType")}
              </Select>)}
            </Form.Item>
            <Form.Item label="일자 선택">{getFieldDecorator("processDate", {
              initialValue: [moment(), moment()]
            })(<RangePicker size="small" style={{width: "220px"}} allowClear={false} format='YYYY-MM' mode={['month', 'month']} />)}</Form.Item>
            <Form.Item className="search-buttons">
              <Button size="small" onClick={this.method.clickSearch}>{locale['label.search']}</Button>
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

const WrappedMonthSearch = Form.create({name:'pmonth_search'})(MonthSearch)
export default class RequestProcessMonth extends React.Component {
  method = {
    search: (params) => {
      let _this = this
      urmsc.ajax({
        type: 'GET',
        url: '/URM/api/stat/process/month',
        data: params,
        success: function(res) {
          _this.refs.list.setState({items: res})
        }
      })
    }
  }

  codeList = () => {
    let codeList = this.props.commonCode
    return codeList ? codeList : []
  }

  render() {
    return (
      <div className="urm-panel" style={{minWidth: 1345}}>
        <WrappedMonthSearch codeList={this.codeList()} search={this.method.search} />
        <ProcessList ref="list" />
      </div>
    );
  }
}
