// react-front/src/components/process/log/list/LogDeferred-list.jsx
import React from 'react'
import { Table, Tabs } from 'antd'
import * as urmsc from '@/urm-utils'

export default class LogDeferredList extends React.Component {
  state = {
    items: [],
    details: [],
    errors: [],
    type: 'log',
  }

  method = {
    getDetails: (record, _this) => {
      let params = {
        type: _this.props.devType,
        processDate: record.processDate,
        interfaceId: record.interfaceId,
      }
      urmsc.ajax({
        type: 'GET',
        url: '/URM/api/process/log/deferred/detail',
        data: params,
        success: function(res) {
          _this.setState({details: res})
        }
      })
    },
    
    changeTab: (key) => {
      this.setState({type: key})
    }
  }

  getRowKey = (list, record) => {
    return list.indexOf(record)
  }

  render() {
    return (
      <div className="urm-list">
        <Tabs defaultActiveKey="common" onChange={this.method.changeTab}>
          <Tabs.TabPane tab="로그데이터" key="log">
            <Table className="table-striped upper-list" scroll={{y: 400}}
              dataSource={this.state.items} pagination={false} bordered
              size="small" rowKey={(record) => ( this.getRowKey(this.state.items, record) )}
              onRow={(record, index) => {
                return {
                  onDoubleClick: e => { this.method.getDetails(record, this) }
                }
              }
            }>
              <Table.Column title="인터페이스ID" dataIndex="interfaceId" width="250px" />
              <Table.Column title="시작 시간" dataIndex="startTime" />
              <Table.Column title="종료 시간" dataIndex="endTime" />
              <Table.Column title="총 건수" dataIndex="totalCount" />
              <Table.Column title="성공 건수" dataIndex="successCount" />
              <Table.Column title="실패 건수" dataIndex="failCount" />
            </Table>

            <hr />

            <Table className="table-striped"
                dataSource={this.state.details} pagination={false} bordered
                size="small" rowKey={(record) => ( this.getRowKey(this.state.details, record) )}>
              <Table.Column title="인터페이스ID" dataIndex="interfaceId" width="215px" />
              <Table.Column title="시스템" dataIndex="appId" width="215px" />
              <Table.Column title="처리일자" dataIndex="processDate" />
              <Table.Column title="시작 시간" dataIndex="startTime" />
              <Table.Column title="종료 시간" dataIndex="endTime" />
              <Table.Column title="총 건수" dataIndex="totalCount" />
              <Table.Column title="성공 건수" dataIndex="successCount" />
              <Table.Column title="실패 건수" dataIndex="failCount" />
            </Table>
          </Tabs.TabPane>
          <Tabs.TabPane tab="오류데이터" key="error">
            <Table className="table-striped"
                dataSource={this.state.errors} pagination={false} bordered
                size="small" rowKey={(record) => ( this.getRowKey(this.state.errors, record) )}>
              <Table.Column title="인터페이스ID" dataIndex="interfaceId" width="145px" />
              <Table.Column title="처리 일자" dataIndex="processDate" width="110px" />
              <Table.Column title="에러 시간" dataIndex="messageTime" width="120px" />
              <Table.Column title="시스템" dataIndex="appId" width="145px" />
              <Table.Column title="오류데이터" dataIndex="errorContents" ellipsis />
              <Table.Column title="자세한에러" dataIndex="errorDataContents" ellipsis />
            </Table>
          </Tabs.TabPane>
        </Tabs>
      </div>
    );
  }
}

// vue-front/src/components/process/log/list/LogDeferredList.vue
<template>
  <div class="urm-list">
    <el-tabs v-model="dataType">
      <el-tab-pane label="로그데이터" name="log">
        <el-table :data="items" @row-dblclick="handleRowDblclick" :height="mainHeight"
            border stripe :row-key="$randomRowKey">
          <el-table-column label="인터페이스 ID" prop="interfaceId" width="250"/>
          <el-table-column label="시작 시간" prop="startTime"/>
          <el-table-column label="종료 시간" prop="endTime"/>
          <el-table-column label="총 건수" prop="totalCount"/>
          <el-table-column label="성공 건수" prop="successCount"/>
          <el-table-column label="실패 건수" prop="failCount"/>
        </el-table>

        <hr />
        <el-table :data="details" :height="detailHeight" border stripe :row-key="$randomRowKey">
          <el-table-column label="인터페이스ID" prop="interfaceId" width="215"/>
          <el-table-column label="시스템" prop="appId" width="215"/>
          <el-table-column label="처리일자" prop="processDate"/>
          <el-table-column label="시작 시간" prop="startTime"/>
          <el-table-column label="종료 시간" prop="endTime"/>
          <el-table-column label="총 건수" prop="totalCount"/>
          <el-table-column label="성공 건수" prop="successCount"/>
          <el-table-column label="실패 건수" prop="failCount"/>
        </el-table>
      </el-tab-pane>

      <el-tab-pane label="오류데이터" name="error">
        <el-table :data="errors" :height="listHeight" border stripe :row-key="$randomRowKey">
          <el-table-column label="인터페이스 ID" prop="interfaceId" width="145"/>
          <el-table-column label="처리 일자" prop="processDate" width="110"/>
          <el-table-column label="에러 시간" prop="messageTime" width="120"/>
          <el-table-column label="시스템" prop="appId" width="145"/>
          <el-table-column label="오류데이터" prop="errorContents" :show-overflow-tooltip="true"/>
          <el-table-column label="자세한에러" prop="errorDataContents" :show-overflow-tooltip="true"/>
        </el-table>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script>
import LogList from './LogList'

export default {
  mixins: [LogList],
  props: {
    items: {
      type: Array,
      default: () => [],
    },
  },
  data () {
    return {
      listHeight: 'calc(100vh - 245px)',
      mainHeight: 'calc((100vh - 215px)/2)',
      detailHeight: 'calc((100vh - 215px)/2 - 50px)',
      path: 'deferred',
      dataType: 'log',
      errors: [],
    }
  },
  methods: {
  },
}
</script>
