// react-front/src/components/rule/list/System-list.jsx
import React from 'react'
import { Table, Button } from 'antd'
import { Form, Input, Select } from 'antd'

import RuleList, { RuleSearch } from './RuleList'
import * as urmsc from '@/urm-utils'

const locale = urmsc.locale

class SystemSearch extends RuleSearch {
  method = {
    ...this.method,

    renderOpts: (key) => {
      return urmsc.getSubListByKey(this.props.codeList, 'kind', urmsc.CODEKEY[key])
              .map((it) => <Select.Option key={it.code} value={it.code}>{it.name}</Select.Option>)
    },
  }

  render() {
    const { getFieldDecorator } = this.props.form

    return (
      <div className={'search-bar ' + this.props.path}>
        <Form colon={false}>
          <div className="row">
            <Form.Item label={locale['label.systemId']}>{getFieldDecorator("id")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.systemName']}>{getFieldDecorator("name")(<Input size="small" className="search-name" />)}</Form.Item>
            <Form.Item label={locale['label.host']}>{getFieldDecorator("hostId")(<Input size="small" className="search-id" />)}</Form.Item>
            <Form.Item label={locale['label.systemType']}>
              {getFieldDecorator("type", {initialValue: ""})(<Select size="small" className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("sysType")}
              </Select>)}
            </Form.Item>
            <Form.Item label={locale['label.devType']}>
              {getFieldDecorator("devType", {initialValue: ""})(<Select size="small" className="search-id">
                <Select.Option value="">ALL</Select.Option>
                {this.method.renderOpts("devType")}
              </Select>)}
            </Form.Item>
            <Form.Item className="search-buttons">
              <Button size="small" onClick={this.method.clickSearch}>{locale['label.search']}</Button>
              {this.method.renderButton(
                <div className="inline">
                  <Button size="small" onClick={this.method.clickAdd}>{locale['label.add']}</Button>
                  <Button size="small" type="danger" onClick={this.method.clickDelete} disabled={!this.props.canDelete()}>{locale['label.delete']}</Button>
                </div>
              )}
            </Form.Item>
          </div>
        </Form>
      </div>
    );
  }
}

class SystemList extends RuleList {
  render() {
    return (
      <div className="urm-list">
        <WrappedSystemSearch {...this.props} search={this.method.search} delete={this.method.clickDelete} canDelete={this.method.isPageDelete} />
        <Table className="table-striped"
          dataSource={this.state.items} pagination={false} bordered
          size="small" /*scroll={{ y: 500 }}*/ rowKey="id"
          onRow={this.onRow}>
          <Table.Column title={locale['label.systemId']} dataIndex="id" width="130px"/>
          <Table.Column title={locale['label.systemName']} dataIndex="name" ellipsis />
          <Table.Column title={locale['label.systemType']} dataIndex="type" width="100px" render={(val) => ( this.method.getTypeStr('sysType', val) )}/>
          <Table.Column title={locale['label.devType']} dataIndex="devType" width="90px" render={(val) =>  ( this.method.getTypeStr('devType', val) )}/>
          <Table.Column title={locale['label.host']} dataIndex="hostId" width="165px" ellipsis />
          <Table.Column title={locale['label.ip']} dataIndex="ip" width="165px" ellipsis />
          <Table.Column title={locale['label.port']} dataIndex="port" width="85px" />
          <Table.Column title={locale['label.dbType']} dataIndex="dbType" width="95px" render={(val) =>  ( this.method.getTypeStr('dbType', val) )}/>
          <Table.Column title={locale['label.dbName']} dataIndex="dbName" width="155px" ellipsis />
          {this.method.renderButton(
            <Table.Column className="operations" width="85px" render={(val) => 
              (<div>
                <Button icon="edit" onClick={e => { this.method.clickEdit(val.id) }} title={locale['label.modify']} />
                <Button icon="delete" type="danger" onClick={e => { this.method.clickDelete([val.id]) }} title={locale['label.delete']} disabled={!this.method.isPageDelete()} />
              </div>)}
            />
          )}
        </Table>
      </div>
    );
  }
}

const WrappedSystemSearch = Form.create({name:'system_search'})(SystemSearch)
export default SystemList

// vue-front/src/components/rule/list/SystemList.vue
<template>
  <div class="urm-list">
    <div class="search-bar">
      <el-form :inline="true">
        <el-form-item :label="$t('label.systemId')">
          <el-input v-model="sparam.id" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.systemName')">
          <el-input v-model="sparam.name" class="search-name" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.host')">
          <el-input v-model="sparam.hostId" class="search-id" @change="search"/>
        </el-form-item>
        <el-form-item :label="$t('label.systemType')">
          <el-select v-model="sparam.type" class="search-id" @change="search">
            <el-option value="" label="ALL"/>
            <el-option v-for="type in sysTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('label.devType')">
          <el-select v-model="sparam.devType" class="search-id" @change="search">
            <el-option value="" label="ALL"/>
            <el-option v-for="type in devTypes" :value="type.code" :label="type.name" :key="type.code"/>
          </el-select>
        </el-form-item>
      </el-form>
      <div class="search-buttons">
        <el-button @click="search">{{$t('label.search')}}</el-button>
        <el-button @click="clickEdit()" v-if="!onlySearch">{{$t('label.add')}}</el-button>
        <el-button @click="clickDelete('selected')" type="danger" v-if="!onlySearch" plain>{{$t('label.delete')}}</el-button>
      </div>
    </div>
    
    <el-table ref="table" :data="items" @row-dblclick="handleRowDblclick" :height="listHeight" border class="table-striped">
      <el-table-column type="selection" width="40" v-if="!onlySearch"/>
      <el-table-column :label="$t('label.systemId')" prop="id" width="130"/>
      <el-table-column :label="$t('label.systemName')" prop="name" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.systemType')" width="100">
        <template slot-scope="scope">
          <span>{{getTypeStr('sysType', scope.row.type)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.devType')" width="90">
        <template slot-scope="scope">
          <span>{{getTypeStr('devType', scope.row.devType)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.host')" prop="hostId" width="165" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.ip')" prop="ip" width="165" :show-overflow-tooltip="true"/>
      <el-table-column :label="$t('label.port')" prop="port" width="85"/>
      <el-table-column :label="$t('label.dbType')" width="95">
        <template slot-scope="scope">
          <span>{{getTypeStr('dbType', scope.row.dbType)}}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('label.dbName')" prop="dbName" width="155" :show-overflow-tooltip="true"/>
      <el-table-column width="85" class-name="edit-cell operations" v-if="!onlySearch">
        <template slot-scope="scope">
          <div>
            <el-button icon="el-icon-edit" @click.stop="clickEdit(scope.row.id)"/>
            <el-button icon="el-icon-delete" type="danger" @click.stop="clickDelete(scope.row.id)" plain/>
          </div>
        </template>
      </el-table-column>
    </el-table> 
  </div>
</template>

<script>
import RuleList from './RuleList'
import RuleUtil from '@/components/rule/RuleUtil'

export default {
  mixins: [RuleList],
  props: {
    sysTypes: {
      type: Array,
      default: function () {
        console.log('set default sysTypes')
        let kind = RuleUtil.CODEKEY.sysType
        return this.$store.state.codes.filter(code => (code.kind === kind))
      }
    },
    devTypes: {
      type: Array,
      default: function () {
        console.log('set default devTypes')
        let kind = RuleUtil.CODEKEY.devType
        return this.$store.state.codes.filter(code => (code.kind === kind))
      }
    },
  },
  data () {
    return {
      path: 'system',
      sparam: {
        ...this.sparam,
        type: '',
        devType: '',
      },
    }
  },
  methods: {
  },
}
</script>
